### ISSUE TITLE
[Suggestion] Change the color of the anchor texts on "About AnkiDroid" screen from red to blue

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#11004]
The color of the following icon looks nice. 
![image](https://user-images.githubusercontent.com/10436072/164433106-69febdd9-3873-473c-9b43-f50f290e39c9.png)

The challenge to change the color of toggle switches to blue (#10909) seems to be wonderful, too (@UvrajSB thanks!).
![image](https://user-images.githubusercontent.com/10436072/164438412-85df8cad-17d2-40b0-9248-2d34835143cf.png)

I think that the following screen will also be more attractive if the color of its anchor texts is "AnkiDroid blue" like one of the icon above .
![image](https://user-images.githubusercontent.com/10436072/164434737-12d81b47-3518-45cf-b729-e68c790203cc.png)
(`Settings` -> `Advanced` -> `About AnkiDroid`)

**Comment by BrayanDSO** [comment]
Same applies to changelog

**Comment by rushikeshsuryawanshi** [comment]
Can I work on this ?

**Comment by UvrajSB** [comment]
> Can I work on this ?

No issues from my end, you can go forward

**Comment by HuWeiyy** [comment]
Is my solution correct?
In my pull request[#11369](https://github.com/ankidroid/Anki-Android/pull/11369), I change the color of the anchor text to blue```#0277BD```, and when I click and hold the anchor text, the color of the anchor text will change to green```#00CC99```.
![无标题2](https://user-images.githubusercontent.com/92869272/168962001-c31da28b-21cd-4413-8db8-e3c59db43761.png)

**Comment by snowtimeglass** [comment]
@HuWeiyy sorry for my late reply. The blue looks nice to me, thanks. 

Though the green is also good, the choice of the color may be arguable as @BrayanDSO says: 

> I'd rather if it used the default link color every browser uses, so it passes accessibility scanner, keep it familiar/simple, and eliminates the need for discussion about colors.

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/11369#issuecomment-1131827963_

I agree with his opinion. To keep the color familiar/simple is more desirable, I think.

**Comment by david-allison** [comment]
@BrayanDSO I believe this is fixed, could you link the PR it was fixed in

**Comment by BrayanDSO** [comment]
Info.kt (the activity with the red links) isn't gone yet as the changelog still uses it, so the issue is still valid, although it should be fixed soon.
