### ISSUE TITLE
[Bug] Last Deck name is "" if `A::` is created

### ISSUE THREAD

**Issue by dorrin-sot** [ankidroid/Anki-Android#11120]
###### Reproduction Steps

1. Create a deck with name `A::`

###### Expected Result
the name of the last child deck should be `blank`

###### Actual Result
its name is "" (empty string)

###### Debug info
```
AnkiDroid Version = 2.16alpha61

Android Version = 11

Manufacturer = unknown

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Android SDK built for x86 Build/RSR1.210210.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36

ACRA UUID = 6a83592c-15b2-4fc2-ba97-73f54beb34b8

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

```
###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Fixed in #10966 I believe

**Comment by RogerDTZ** [comment]
Hey @david-allison , I believe that #10966 does not fix the bug.

The hierarchy resolver for **deck** is different from the one for **tag**.

https://github.com/ankidroid/Anki-Android/blob/b1a0974c91edb64db71dfc49b3dff5be03e4a512/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L684-L721

We should have somebody fix this method.

**Comment by dorrin-sot** [comment]
If it is accepted and @RogerDTZ isn't accepting it can I take it? 👀

**Comment by krmanik** [comment]
The earlier bug related to `::DeckName` fixed in #11045 but now this bug is in `DeckName::`.
@dorrin-sot Sure!

**Comment by Tinkidinki** [comment]
Out of curiosity, (1) what does "blank" mean? (2) Why is it a problem if the deck name is "" (empty string) rather than blank?

**Comment by dorrin-sot** [comment]
>(1) what does "blank" mean? (2) Why is it a problem if the deck name is "" (empty string) rather than blank?

It's just a placeholder for empty string ("") since it doesn't look good UI-wise for there to be a deck with no name
