### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ahielg** [ankidroid/Anki-Android#11569]
###### Reproduction Steps

1. Open AnkiDroid
2. Click on refresh arrows

###### Expected Result
 The three dots menu will not disappear.

###### Actual Result
 The three dots menu disappear

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! I believe this is fixed in the latest releases: https://github.com/ankidroid/Anki-Android/releases

You removed the debug info section on our template, which includes valuable information like what version you are using, so I can't say if you have tried the latest release or not, but you should give it a try, I think it will work

**Comment by ahielg** [comment]
This issue still happening but only after learning notes and then going back to the main screen.

**Comment by ahielg** [comment]
still searching for solutions

**Comment by mikehardy** [comment]
> Hi there! I believe this is fixed in the latest releases: https://github.com/ankidroid/Anki-Android/releases

This bug had no actual title, the steps to reproduce are not enumerated in one single spot, and I don't recall any feedback to my suggestion of trying the latest alphas, which is why this is stale.

**Comment by ahielg** [comment]
You are right, I was sure the alpha version is already in the play store.
But now I noticed that when there is a red dot on the sync button, it will not disappear if you sync using pull down the screen.

**Comment by mikehardy** [comment]
Okay - diving even more deeply into that, there's a new code pathway for sync even inside 2.16 that is not enabled for everyone yet but has received a good bit of testing. Reproducing behavior on the old pathway will not mean much since it will be retired - so if you go into settings --> advanced and turn on "new schema support", that is the gold standard for testing sync-related items.

We are aware that progress reporting for the media sync phase is not good yet - we have a solution designed out roughly for that (a sticky progress notification while sync happens, with the rest of the UI unblocked), but other than that...it should work? (and even then it is working, just no media sync progress reporting)
