### ISSUE TITLE
[Bug] RAM usage keeps increase if deck use custom font

### ISSUE THREAD

**Issue by Myuki** [ankidroid/Anki-Android#12034]
###### Reproduction Steps

1. Use custom font for deck.

```
@font-face {
 font-family: Noto Sans CJK JP; src: url('_NotoSansCJKjp-Regular.ttf');
}

.card {
 font-family: Noto Sans CJK JP;
 font-size: 20px;
 text-align: center;
 color: black;
 background-color: white;
}
```

2. Keep review card and always choose `again` for every card. `again` is just easier for reproduction, others is also reproducible.

###### Expected Result

RAM usage should keep in an acceptable level.

###### Actual Result

RAM usage keeps increase as the more card had been review, even reach 8 GB. AnkiDroid may crash because webview out of memory.

![2022-8-13 1](https://user-images.githubusercontent.com/27203797/184797414-c474fa07-ec57-4943-a441-8dbf3814241a.jpg)

###### Debug info

AnkiDroid Version = 2.16alpha77

Android Version = 12

Manufacturer = samsung

Model = SM-T865N

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-T865N Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Safari/537.36

ACRA UUID = ef79a33e-622a-4382-9b64-0a069a506994

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

##### More info

This problem can be workarounded by exit the study and reenter the study again. Don't review all cards at one time.

I had met this problem on my old Galaxy S8+ and also reproduce on OnePlus 9R. It seems like some resource of reviewed card is still in the memory, even the card will never appear again in this study. Every time to review a card, new or not, RAM usage keep increasing.

I had tested 2 fonts and 3 decks. All reproducible.

~~##### Tested sample~~

~~Tested Fonts: <https://mega.nz/file/C9thSJ6I#OjVip_ySxZ40B-6bWvW9kkJ3hfgPP_WbpNRl-qICCQ4>~~

~~Tested Decks: <https://mega.nz/file/il8CGZrJ#gPWxibyMOK7kZ_tOKWJ3taCSTH6KMIoIohdhZXI0hKY>~~

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Myuki** [comment]
I want to do more test. It seems to relate to the deck.

**Comment by dawmd** [comment]
I can't check the decks now, but I've noticed the same issue when using the app for a relatively longer time (I think 10+ minutes). Anki suddenly starts consuming so much RAM that restarting it seems to be the only solution. From what it looks like the deck I use has been removed from the website and I'm not sure if I can share it. What might be relevant, though, is the font doesn't seem to be custom. The cards aren't very complex, either. The deck has 17,000+ cards, but it's divided into "categories" and the one I exclusively use has 4,000+ of them.

**Comment by CjiqL** [comment]
Hi, I had the same problem when using custom fonts.
Ankidroid's memory usage would increase as I reviewed the cards, until the device became stuttering and could no longer be used.
I'm almost going crazy because my device only has 4G RAM, so every 50 or so cards I need to restart ankidroid.
I encountered this problem when using version 2.15, and the problem still exists after upgrading to 2.16alpha89.
I agree that ankidroid does not clear the resources of the displayed cards but keeps them in memory.
Because when I don't use custom fonts I don't have problems like this.
I use onxy's boox note3 device.
I would be very grateful if you could fix this.
thanks.

Below is some information.
```
AnkiDroid Version = 2.16alpha89

Android Version = 10

Manufacturer = ONYX

Model = Note3

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Note3 Build/2022-11-11_11-48_3.3.1_8e8c94e; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Safari/537.36

ACRA UUID = 1fd466c7-dca3-4c7e-903d-40d2b1d67c82

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
This is the css of my card
```
@font-face { font-family: yh; src: url("_NotoSansSC-Regular.otf") format("opentype");}
.card {
    font-family: yh;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
```

**Comment by mikehardy** [comment]
It's not that ankidroid doesn't clear them, it's that the system built-in webview doesn't clear them, this is unfortunately an "in-between" problem, that is, the problem is in between AnkiDroid (which uses standard APIs to use the standard built-in system WebView for card display) and the system WebView component (which loads the card for display inlcluding fonts)

I'm not sure what we can do here really. As I type that I thought of something sort-of horrible but also *possible*. Maybe every N reviews (user configurable) we could discard the WebView and make a new one. That would make display for the next card slower but would stop the problem from getting to the point where it was unusable.

I'll reopen in case someone wants to experiment with that idea

**Comment by fxmarty** [comment]
Since I restarted using Anki after ~10 min of review Anki crashes. I study with a custom font as OP, so I guess that's the reason why.

**Comment by mikehardy** [comment]
In my experience custom fonts are *always* the reason why. Using the lightest font for your use case is the mitigation strategy, disappointing as I know that is

**Comment by rotmoss** [comment]
> It's not that ankidroid doesn't clear them, it's that the system built-in webview doesn't clear them, this is unfortunately an "in-between" problem, that is, the problem is in between AnkiDroid (which uses standard APIs to use the standard built-in system WebView for card display) and the system WebView component (which loads the card for display inlcluding fonts)
> 
> I'm not sure what we can do here really. As I type that I thought of something sort-of horrible but also _possible_. Maybe every N reviews (user configurable) we could discard the WebView and make a new one. That would make display for the next card slower but would stop the problem from getting to the point where it was unusable.
> 
> I'll reopen in case someone wants to experiment with that idea

I might be able to fix this issue using the method you suggested, i don't have a phone with alot of memory, so this problem is driving me crazy!!! 

The wierd thing is that the WebvView even seems to be leaking memory when ankidroid is running in the background. Maybe it's worth trying to set the creation of a new WebView on a timer insted of per card?

**Comment by fxmarty** [comment]
not stale

**Comment by Myuki** [comment]
The problem seems been fixed by WebView. I just realize the problem disappeared for a period of time. I am not sure which version fix that. My current WebView version is 111.0.5563.116. Could anyone confirm that?

**Comment by epistularum** [comment]
I'm still crashing on webview 111.0.5563.115.

**Comment by suyiiyii** [comment]
Unfortunately, the problem seems to still exist with webview 111.0.5563.116 and alpha 97 on my device

**Comment by Myuki** [comment]
not stale
