### ISSUE TITLE
[Bug]2.16Alpha91 Card number after Rebuild  Option in Filtered Deck not displaying on first try.

### ISSUE THREAD

**Issue by LBX1002** [ankidroid/Anki-Android#12924]
###### Reproduction Steps

1. I have a filtered deck that retrieves a certain group of cards.
2. I long press on the name to bring up the options menu
3. I tap Rebuild. Menu closes but
4. Number of cards in the deck does not display.
5. I slightly tap on the deck name again.
6. Number of cards in deck now displays correctly.

###### Expected Result
Number of cards in the filtered deck to display after choosing Rebuild.

###### Actual Result
Number of cards does not display. I tap again slightly on the deck name to bring up the number.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
@LBX1002  Can you share the debug info

**Comment by LBX1002** [comment]
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = samsung

Model = SM-F926U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-F926U1 Build/SP2A.220305.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Safari/537.36

ACRA UUID = 366705ad-10a3-45fd-86a5-c237e77a8071

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by LBX1002** [comment]
I believe the deck page does not automatically refresh (after selecting the rebuild from the drop down menu) until I manually perform another activity on the deck page.

**Comment by LBX1002** [comment]
https://user-images.githubusercontent.com/61126947/205525691-e60a7c9b-eb3a-49a9-9628-5c2d9296019c.mp4

**Comment by criticalAY** [comment]
Looks like this issue to some what similar to the sync red dot there a refresh is required to update the info

**Comment by LBX1002** [comment]
> Looks like this issue to some what similar to the sync red dot there a refresh is required to update the info

Exactly. The red dot issue appeared in alpha89 and was fixed in alpha90.

**Comment by MagTun** [comment]
I also have the number on filtered deck not being updated after a rebuilt. 

> > Looks like this issue to some what similar to the sync red dot there a refresh is required to update the info
> 
> Exactly. The red dot issue appeared in alpha89 and was fixed in alpha90.

@LBX1002 , I have installed AnkiDroid 2.16alpha91 and I still have the red dot with a "!" after a sync.

**Comment by LBX1002** [comment]
> I also have the number on filtered deck not being updated after a rebuilt.
> 
> > > Looks like this issue to some what similar to the sync red dot there a refresh is required to update the info
> > 
> > 
> > Exactly. The red dot issue appeared in alpha89 and was fixed in alpha90.
> 
> @LBX1002 , I have installed AnkiDroid 2.16alpha91 and I still have the red dot with a "!" after a sync.

This page refresh issue reappeared in 2.16Apha91 after being fixed in 2.16Apha90.  Hopefully it will be fixed again in 2.16Apha92

**Comment by MagTun** [comment]
Thanks for the new update. I have just installed it (2.16Apha92):
- the bug with red dot with a "!" after a sync is fixed.
- the card number after selecting "empty" on a filtered deck is fixed
- but the card number after a "rebuilt" on a filtered deck is not displayed (a second click on the filtered deck updates it though)

**Comment by MagTun** [comment]
Thanks for the new update. I have just installed it (2.16Apha92):
- the bug with red dot with a "!" after a sync is fixed.
- the card number after selecting "empty" on a filtered deck is fixed
- but the card number after a "rebuilt" on a filtered deck is not displayed (a second click on the filtered deck updates it though)

**Comment by MagTun** [comment]
I have installed 2.16alpha94 and I still have the same problems:

- when I sync, the red dot on the sync icon remains (though it is gone after a second sync right after the first one)
- the cards number after a "rebuilt" on a filtered deck is not updated (a second click on the filtered deck updates it though)

```
AnkiDroid Version = 2.16alpha94

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.18 Mobile Safari/537.36

ACRA UUID = a67adf2f-519a-49fe-bd85-4df9f69d393d

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```
