### ISSUE TITLE
import is too slow 

### ISSUE THREAD

**Issue by chenkeao** [ankidroid/Anki-Android#12993]
I tried importing a 200M deck, but the import was too slow.  I import it in seconds using anki on linux and hours on android.  I don't know why this is happening, but it's getting me out of use.
android version: android 13
ankidroid version: 2.15.6, download from Google play

**Comment by BrayanDSO** [comment]
Try using the latest alpha with the setting `Use the new backend` enabled (you can find it on `Settings - Advanced`)

**Comment by BrayanDSO** [comment]
Trying this may help you also https://github.com/ankidroid/Anki-Android/issues/9941#issuecomment-984906096

**Comment by mikehardy** [comment]
You may also work around this by doing the import into anki desktop then syncing to ankiweb and syncing to ankidroid instead of importing directly on ankidroid. Though the new backend in the new releases will hopefully make it quick for you, very interested in your report on success (or not) with new backend

**Comment by chenkeao** [comment]
> You may also work around this by doing the import into anki desktop then syncing to ankiweb and syncing to ankidroid instead of importing directly on ankidroid. Though the new backend in the new releases will hopefully make it quick for you, very interested in your report on success (or not) with new backend

Thanks a lot, I'll try it now

**Comment by david-allison** [comment]
Should be resolved in the alpha (using a volatile directory for storage).

Pending a better implementation of this for F-Droid/alphas: https://github.com/ankidroid/Anki-Android/compare/main...david-allison:Anki-Android:scoped-storage-permissions 

Closing as completed

**Comment by dspjm** [comment]
Any solution now? Still happening on 2.15.6. Especially when there are numerous media files to import.

**Comment by dspjm** [comment]
Any solution now? Still happening on 2.15.6. Especially when there are numerous media files to import. Can I know which version was this fixed?

**Comment by SanjaySargam** [comment]
> Any solution now? Still happening on 2.15.6. Especially when there are numerous media files to import. Can I know which version was this fixed?

https://github.com/ankidroid/Anki-Android/releases
use latest release from here

**Comment by JamesAM86** [comment]
The same is still occurring for me with large decks, too, oddly enough.
Hopefully a fix will be figured out soon enough despite the difficulties.
