### ISSUE TITLE
[Bug] gestures are hidden in horizontal mode

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13432]
As seen on
![Screenshot_20230312-100755_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/224535121-4ee5a077-b570-4a02-b5ca-32df5ec6130a.jpg)

For example you can’t see that right now, double tap is selected.

Someone should test on smartphone too. This is a galaxy tab.
Ankidroid updated yesterday from main

Ping @BrayanDSO

**Comment by pavreh** [comment]
This is on a smartphone.
![Screenshot_20230312_103624_AnkiDroid.png](https://user-images.githubusercontent.com/10192661/224536632-23cf5c80-2797-477a-bb05-fa065223ff48.png)

**Comment by Arthur-Milchior** [comment]
Thanks @pavreh

**Comment by pratyaksh1610** [comment]
@Arthur-Milchior Can you PTAL at #13413  I have updated the name of the function.
Thanks.

**Comment by criticalAY** [comment]
One possible solution is to wrap the content in scroll view but that comes with a disadvantage in landscape mode that the swipe up gesture could not be set by user otherwise things would work fine

**Comment by mikehardy** [comment]
I just merged a fix that will lock orientation as a temporary fix (thank you @criticalAY !) and it will be in all releases >= 2.16.0beta3 (that is, not released yet but all future releases)

As mentioned on related PR (quote following) we need to determine what the real solution is (or if one is possible) prior to closing this

-----

> The gesture dialog can be shifted to a fragment but it is not what we want because people usually don't do it and it was discussed on Discord that we will see if we really need the switch to a fragment for this or not but for now this would fix it

**Comment by BrayanDSO** [comment]
#13825 didn't fix this, so I'd argue for a revert.

Build of 94328239e6bd3cb0b0dfefff719944d4abfbcfbd. Tested on my phone (Samsung, Android 13) and on an API 29 emulator

https://github.com/ankidroid/Anki-Android/assets/69634269/92ed5741-9baa-4479-b7fe-9bce90f8bc00

**Comment by BrayanDSO** [comment]
And I think that a dialog fragment is a good idea, not something that "we don't want"

**Comment by criticalAY** [comment]
> And I think that a dialog fragment is a good idea, not something that "we don't want"

This is considered not worth giving time and @oakkitten suggested locking the orientation itself

**Comment by Arthur-Milchior** [comment]
> This shouldn't have happened but I won't put a patch on another patch I will try to shift this to a dialog Fragment or fix this code material dialog itself this time

I beg your pardon, I don't understand what you are planning to do.
Do you agree with @BrayanDSO that we should revert; and then you'll do a fresh start?
Do you mean that you just want to stop working on it altogether (in which case, a revert is also nice)

**Comment by criticalAY** [comment]
I meant that I would fix the root cause of this issue or shift this code to a fragment. I'm having ongoing exams that will get over this week so I'll fix it up after that
