### ISSUE TITLE
[BUG]: Mathjax breaks template

### ISSUE THREAD

**Issue by Dazaisan99** [ankidroid/Anki-Android#13552]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Write any kind of mathjax in the template linked

[template.zip](https://github.com/ankidroid/Anki-Android/files/11158122/template.zip)

### Expected behaviour

Normal form of the template with the styling and the mathjax (on my computer)
![ankiscreen](https://user-images.githubusercontent.com/96884464/230066232-daaa4292-bbfb-4bcd-9da3-e8b76068b6de.jpg)

### Actual behaviour

How ankidroid rendered it :
![ankidroidscreen](https://user-images.githubusercontent.com/96884464/230066270-292b772a-cf4e-4eeb-8eef-4b74fd9c8370.jpg)
Wrong spacing, words going on the line below...

### Debug info

```text
Ankidroid version 2.15.6
Android version 9
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Please try with the latest alpha, mathjax has changed/improved quite a bit since version 2.15.6 and most problems people report are solved: https://github.com/ankidroid/Anki-Android/releases

**Comment by Dazaisan99** [comment]
Sorry, I thought I had already tried on the latest alpha but it turns out it hadn't updated correctly. However, the bug still occurs like it did in 2.15

**Comment by Dazaisan99** [comment]
I have found the issue, the Javascript tried to run before the HTML was loaded, leading to errors because the MathJax took too long to load : https://www.reddit.com/r/Anki/comments/n38ctd/javascript_in_card_not_working_on_ankidroid_works/

The workaround is just wrapping the javascript code with `setTimeout` to make it run after the HTML.

Before closing the issue, is there any better workaround than this ? Setting an arbitrary waiting value like this isn't stable, and creates a little blinking while rendering the card.
