### ISSUE TITLE
Card browser doesn't persist direction of display order (always smallest to largest)

### ISSUE THREAD

**Issue by jgscherber** [ankidroid/Anki-Android#14933]
###### Reproduction Steps

1. Open card browser
2. Observe sort is from smallest to largest
1. Toggle sort
3. Observe sort is now largest to smallest
1. Return to desk screen and back to card browser
1. Sort reverted and is smallest to largest again
1. Check the "change display order" screen
1. Observe the sort claims to be largest to smallest (down-triangle icon)

See video

https://github.com/ankidroid/Anki-Android/assets/6207661/3ad6496c-b5be-451f-b55c-a7c9f15c0619

###### Expected Result

Both display sort field and direction are persisted

###### Actual Result

Only field is persisted and direction is always smallest to largest

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-G981U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G981U1 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 03434583-cd6c-4869-8ed2-d8e7712382df

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, could you try this out on the 2.17 alpha?

We're in the process of making large changes here, but I believe this one is already fixed

**Comment by david-allison** [comment]
Hi @jgscherber 

You gave my previous message a thumbs up, are things working?

Alphas can be found: https://github.com/ankidroid/Anki-Android/releases

I'd recommend `Parallel.A` so it can be run alongside your current AnkiDroid installation

**Comment by jgscherber** [comment]
Sorry I just tried it now on the Parallel-A and the issue still occurs

**Comment by jgscherber** [comment]
When I tried to use Parallel.A for 2.17alpha9 and 2.17alpha10 I get the below error so I can't test

![SmartSelect_20231215_114250_AnkiDroidA.jpg](https://github.com/ankidroid/Anki-Android/assets/6207661/66076fd9-bbe9-403a-a73a-d7f0d2dabf50)

**Comment by mikehardy** [comment]
@jgscherber you may need to go through system preferences to the app settings screen and check storage permissions + manually grant it ?

**Comment by jgscherber** [comment]
It seemed to be an issue with me trying to use the "sync" option on the fresh install. I accidentally installed the 2.16 parallel and the promoted me on selecting the sync option. When I uninstall 2.16 and installed 2.17, it threw that error selecting the "sync" option.

I just tried doing the other menu option and the promoted me to grant the permission. Then once loaded, all my cards were already there, maybe from the original install of the 2.16 sync?

But back to the main issue.... it does appear to be resolved on 2.17, the sort order is maintained when going to the deck screen and back to the card browser.

**Comment by david-allison** [comment]
Great, thanks!
