### ISSUE TITLE
Docs: JavaScript APIs documentation needs updating

### ISSUE THREAD

**Issue by gugutu** [ankidroid/Anki-Android#14953]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I am using JS API in the card: 
```js
var jsApi = { "version": "0.0.1", "developer": "abc@qq.com" };
AnkiDroidJS.init(JSON.stringify(jsApi));
AnkiDroidJS.ankiGetNextTime1();
```

### Expected behaviour

JSAPI is working properly

### Actual behaviour

AnkiDroid pop-up prompt: `Card provided invalid data`

The JS error is as follows: `TypeError: AnkiDroidJS.ankiGetNextTime1 is not a function`

![Screenshot_2023-12-12-15-16-20-007_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/59798823/5ce2993b-cb34-45db-b756-62f54925c683)

### Debug info

```text
AnkiDroid Version = 2.17alpha10 (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2006J10C

Hardware = mt6889

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2006J10C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 756393f7-4e9a-4237-bf56-cce7e9108797

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report!

The API has been updated to 0.0.2, and this contains breaking changes. Please see the following issue for a working demo:

* https://github.com/ankidroid/Anki-Android/pull/14564

@krmanik, FYI: We need to update [the docs](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API). I'm moving this to 'good first issue', as a new contributor should be able to produce fixed documentation, but if you have time, it's obviously open to you

**Comment by krmanik** [comment]
@gugutu 
You have to update similar to this.
```js
var jsApiContract = { "version": "0.0.2", "developer": /* enter your email here */ };
var api = new AnkiDroidJS(jsApiContract);
// now use api object for calling js api
```

Currently out of time, so this issue open to new contributor to update the docs.

**Comment by gugutu** [comment]
> @gugutu You have to update similar to this.
> 
> ```js
> var jsApiContract = { "version": "0.0.2", "developer": /* enter your email here */ };
> var api = new AnkiDroidJS(jsApiContract);
> // now use api object for calling js api
> ```
> 
> Currently out of time, so this issue open to new contributor to update the docs.

Thanks, it's working very well now.

**Comment by elli-hae** [comment]
Do I understand correctly that basically only the usage example has to be updated in [the docs](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#usage)?

**Comment by mikehardy** [comment]
> Do I understand correctly that basically only the usage example has to be updated in [the docs](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#usage)?

I think yes - but I think it's more than one example as all the methods are async now and I think all the various one-liner examples also should be updated to be an `await <function>` or similar? Though I confess I haven't tried that - not sure if HTML input javascript handlers can await or not. If they can't I guess it has to be the pre-historic `function().then{() => { dosomething(); }.finally(() => { handleError(); }` or similar

**Comment by david-allison** [comment]
It's worthwhile to go through the code before you write it

I think that the sample code on the linked PR will be sufficient: this converts the calls to be async and uses the new object to access the API

**Comment by elli-hae** [comment]
Hi, I was looking into this (it took a bit since I'm not that familiar with JS) but then got sick, and in the meantime @krmanik updated the docs :)
I just tried it out again and noticed that a lot of the methods do not work for me (using the detailed example from https://github.com/ankidroid/Anki-Android/pull/14564#issue-1953332634 and just testing various one-liners), including "mark card", "set flag", "bury card",  while "show answer", "again", "hard" etc. work well. I'm a bit confused about this since I think I remember the methods working when I first tried them out a few weeks ago. I just wanted to note that in case it's not simply wrong implementation on my part.

**Comment by david-allison** [comment]
@krmanik @BrayanDSO 

https://github.com/ankidroid/Anki-Android/commit/0beeb7010c0b4f5f58f12010128b494c9cedb001 appears to remove the JS API from the Previewer. Was this an intentional change?

**Comment by david-allison** [comment]
Done: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

**Comment by BrayanDSO** [comment]
I did that change based in this (still present in main):

https://github.com/ankidroid/Anki-Android/blob/abb6a36681a0fe0e0dca04d02468c6c40c81e9fe/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt#L189-L193

From memory, there was a TODO in the API discussion to separate what every screen can do, so the previewer won't start rating, suspending, burying, etc

**Comment by krmanik** [comment]
> @krmanik @BrayanDSO
> 
> [0beeb70](https://github.com/ankidroid/Anki-Android/commit/0beeb7010c0b4f5f58f12010128b494c9cedb001) appears to remove the JS API from the Previewer. Was this an intentional change?

It is intentional because it may mark card or flag card, so in previewer default value are provided.

**Comment by david-allison** [comment]
It feels more broken than it should be:

```
03:16:31.506 chromium                             I  [INFO:CONSOLE(112)] "Request error: TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (112)
03:16:31.506                                      I  [INFO:CONSOLE(112)] "Request error: TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (112)
03:16:31.506                                      I  [INFO:CONSOLE(112)] "Request error: TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (112)
03:16:31.506                                      I  [INFO:CONSOLE(90)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (90)
03:16:31.506                                      I  [INFO:CONSOLE(90)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (90)
03:16:31.506                                      I  [INFO:CONSOLE(90)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (90)
03:16:31.913 AnkiDroidApp$onCreate                I  CardBrowser::onStop
03:16:31.914 WidgetStatus                         D  WidgetStatus.update(): already running or not enabled
03:16:31.914 AnkiDroidApp$onCreate                I  CardBrowser::onSaveInstanceState
03:16:32.425 rsdroid::logging                     D  STDOUT: [INFO:CONSOLE(112)] "Request error: TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (112)
03:16:32.425                                      D  STDOUT: [INFO:CONSOLE(112)] "Request error: TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (112)
03:16:32.425                                      D  STDOUT: [INFO:CONSOLE(112)] "Request error: TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (112)
03:16:32.425                                      D  STDOUT: [INFO:CONSOLE(90)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (90)
03:16:32.425                                      D  STDOUT: [INFO:CONSOLE(90)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (90)
03:16:32.425                                      D  STDOUT: [INFO:CONSOLE(90)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/scripts/js-api.js (90)
03:16:32.947 EGL_emulation                        D  app_time_stats: avg=39.86ms min=9.37ms max=904.68ms count=39
03:16:34.842                                      D  app_time_stats: avg=111.34ms min=13.25ms max=1632.65ms count=17
```

+ `Card content error, failed to load init.bin`

**Comment by david-allison** [comment]
```
api.ankiAnswerEase1().then(x => console.log(x))
Promise {<pending>}
js-api.js:90          POST http://127.0.0.1/jsapi/answerEase1 net::ERR_CONNECTION_REFUSED
handleRequest @ js-api.js:90
AnkiDroidJS.<computed> @ js-api.js:137
(anonymous) @ VM177:1
js-api.js:112 Request error: TypeError: Failed to fetch
    at AnkiDroidJS.handleRequest (js-api.js:90:36)
    at AnkiDroidJS.<computed> [as ankiAnswerEase1] (js-api.js:137:27)
    at <anonymous>:1:5
handleRequest @ js-api.js:112
await in handleRequest (async)
AnkiDroidJS.<computed> @ js-api.js:137
(anonymous) @ VM177:1
js-api.js:90          Uncaught (in promise) TypeError: Failed to fetch
    at AnkiDroidJS.handleRequest (js-api.js:90:36)
    at AnkiDroidJS.<computed> [as ankiAnswerEase1] (js-api.js:137:27)
    at <anonymous>:1:5
```

**Comment by krmanik** [comment]
I will push the fix, I am checking it now.

**Comment by krmanik** [comment]
@david-allison 
I think we need to revert this commit [0beeb70](https://github.com/ankidroid/Anki-Android/commit/0beeb7010c0b4f5f58f12010128b494c9cedb001), I have checked it and the request can be captured and return the default value in card template viewer but I think it is better to revert it to becuase JS API works by fetching request.

**Comment by david-allison** [comment]
> @david-allison 
> I think we need to revert this commit [0beeb70](https://github.com/ankidroid/Anki-Android/commit/0beeb7010c0b4f5f58f12010128b494c9cedb001), I have checked it and the request can be captured and return the default value in card template viewer but I think it is better to revert it becuase JS API works by fetching request.

Getting `DeckId` is now broken in the previewers. We want to fix this, regardless of whether it is reverting or fixing forwards. Having this request fail isn't a good outcome

I'd prefer to fix forward if possible

@BrayanDSO do you feel this is feasible to do?
