### ISSUE TITLE
[Bug] Change color of Checkbox in AlertDialog 

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15174]
###### Reproduction Steps

1. Go to Manage Space
2. Click on `Delete backups`
3. Click on any one of the Checkbox Item

###### Expected Result
The color must match with App's theme i.e. `@color/material_light_blue_500`

###### Actual Result
The color is default which is light green
![WhatsApp Image 2024-01-08 at 9 33 40 AM](https://github.com/ankidroid/Anki-Android/assets/65113071/6abaea39-d09f-4508-9e84-61dfb4598687)

###### Debug info
AnkiDroid Version = 2.17alpha14-debug (1bb9883e54c132cd1dc3235f8932bbab56590236)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36

ACRA UUID = 499dd159-a9b7-4067-bc7f-31d815ef70de

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by evanOGrady** [comment]
I would like to take on this issue.

**Comment by SanjaySargam** [comment]
Sure go ahead

**Comment by Giyutomioka-SS** [comment]
@evanOGrady Are you still working on this, or can I take this up?

**Comment by evanOGrady** [comment]
@Giyutomioka-SS 
You can take this on. I thought I would have more free time to do this.

**Comment by Thejas775** [comment]
@Giyutomioka-SS are you still working on this or can i be assigned ?

**Comment by Giyutomioka-SS** [comment]
You can take this on.

**Comment by Thejas775** [comment]
@david-allison please assign me this issue

**Comment by david-allison** [comment]
Done, cheers!

**Comment by neeldoshii** [comment]
Seems like issue still exists.

| Light | Dark |
|--------|--------|
| ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/718beaed-53f1-4d4b-a578-5942049d744d) | ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/d3fe12df-d6c9-4f39-b281-6e470a27a779) |

**Comment by david-allison** [comment]
@MorenoTropical could you confirm?

**Comment by MorenoTropical** [comment]
Hi. I had noted in the PR that it would be fixed after that and my other PR #16549 were fixed, but I did the error of putting the issue number after the word Fixes.

I'm sorry for that.

But it should be fixed after my other PR is merged.
