### ISSUE TITLE
[Bug] Missing image handler's message doesn't appear in 2.17alpha17

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15353]
###### Reproduction Steps

1. add a tag leading to a non-existing file into a card, e.g. `<img src="naruto.jpg">`
2. open the card

###### Expected Result

this snackbar appears (2.16.5):

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/fe427bc4-dd61-4057-9041-370fd4aafeb1)

###### Actual Result

it doesn't

###### Debug info
2.17alpha17, built on top of f4172d65147e2531895f0dc4c3419ebfcda0c9da. `full` build

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
For anyone that has the time, I think that a `git bisect` would help finding the cause of this one

**Comment by rohit9625** [comment]
Hey @BrayanDSO 
May I work on this? I know how to use git bisect.

**Comment by rohit9625** [comment]
Can you please refer me to a good commit where the `snackbar` appeared successfully?

**Comment by BrayanDSO** [comment]
Go for it. It worked in e817d891c70a05b86aa10690f5a5d5e2b1c7ad2d

My bet is that 7a65160e0e23e20080091a30abdd4c05fc610e06 is the first bad commit

**Comment by BrayanDSO** [comment]
I was going to fix this, but my timebox has ended before I could come to the final solution. In my research, the causes are:

1. The host used by MissingImageHandler was outdated (fixed in https://github.com/BrayanDSO/Anki-Android/commit/f1edf9d90bdf9511e91c2973fef7c29b211b61f5)
2. `AbstractFlashcardViewer::CardViewerWebClient::onReceivedError` isn't being called for some reason I don't know. I tried to use the same method at the new previewer's webviewclient and it worked there, so I really don't know what is the issue here

**Comment by rohit9625** [comment]
Strange, in my case the **onReceivedErrro** is also not being called. I spent hours of debugging yesterday but still unable to find it.
Today maybe we'll find it 😄

**Comment by rohit9625** [comment]
Does this issue still persist

**Comment by BrayanDSO** [comment]
yes
