### ISSUE TITLE
[BUG]: Zooming in Statistics Page

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16135]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Open Statistics
2. Zoom in then Zoom Out
3. Scroll to the bottom 

### Expected behaviour

everything's normal

### Actual behaviour

page scrolls infinitely. After the Cards Added section it's an infinite empty screen you can scroll through.

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by jainishrpandya** [comment]
I am working on it.

**Comment by jainishrpandya** [comment]
@brishtibheja Can you confirm if this is the issue you mentioned?

https://github.com/ankidroid/Anki-Android/assets/69842037/82e376d1-06b7-43e6-969e-ca87c6c865f5

**Comment by brishtibheja** [comment]
Don't worry. You've got the right one.

**Comment by jainishrpandya** [comment]
@brishtibheja thanks for confirming. I am working on it.

**Comment by jainishrpandya** [comment]
the problem is with the nestedScrollView. Instead we can use LinearLayout.

I Tested it with Linear Layout.

https://github.com/ankidroid/Anki-Android/assets/69842037/708224c1-1528-4184-a589-b1e8c5179d75

**Comment by jainishrpandya** [comment]
@user1823 Yes! This bug appeared after the nestedscrollview added to hide the topbar when scrolled.

**Comment by user1823** [comment]
> the problem is with the nestedScrollView. Instead we can use LinearLayout.
> I Tested it with Linear Layout.

Based on the video, it seems to break the feature added in the above-mentioned PR, i.e., hiding the top bar on scroll.

**Comment by neeldoshii** [comment]
@jainishrpandya Thanks for breaking the cause of the bug. Seems I forgot to test throughly while I implemented hide scroll feature which led 2 more issues.

Can you check, does this help in fixing it?

https://stackoverflow.com/questions/35127845/webview-inside-nestedscrollview-cannot-be-scrolled

**Comment by neeldoshii** [comment]
```diff 
    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
+      android:fillViewport="false"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">
        
 ```
  Did this helped anyway? My spare android device is pretty old which's multiple taps ain't working properly.

**Comment by jainishrpandya** [comment]
I'm sorry for not getting back to you sooner.
I have tested different approaches, but the problem persists. so I think the problem is with the page from where the data is sourced.
maybe I am wrong so can someone double check.

**Comment by BrayanDSO** [comment]
I believe that this is a problem with the interaction of `View` zooming and the appbar properties. This may not be solvable without doing hacks or without a deep understanding of the views that are being used.

I'm removing the `Priority-High` label since this isn't a major distress for the user

**Comment by deysak** [comment]
Hi @jainishrpandya, are you still working on this? If not, I would like to.

**Comment by david-allison** [comment]
@deysak feel free to work on it if you don't get a reply within 24 hours from your comment

Ping me at this point if you want it assigned (only as a formality)
