### ISSUE TITLE
[BUG]: <audio> html tag doesn't always load the whole audio

### ISSUE THREAD

**Issue by iagann** [ankidroid/Anki-Android#16499]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I use ankidroid for 4 years. After one of the recent updates (or maybe it's not even an ankidroid update) for some of the cards, that were perfectly fine before, there is an error "failed to load". Despite that, audio still loads, but only some part of it. Looks similar to a video buffering on youtube, the first part loads, but the rest doesn't.
Windows version works fine. And even in other apps the same audio file is played normally, it's not corrupted.
I found a solution - adding an attribute preload="auto" to the <audio> tag. With that the whole audio loads without problems.

### Expected behaviour

Audio inside the <audio> HTML tag loads fully without errors

### Actual behaviour

For some audios I get an error "failed to load". Despite that, audio still loads, but only some part of it.
adding  preload="auto" to the <audio> tag fixes the problem. It probably forces the browser to preload the whole audio, instead of loading it in chunks

### Debug info

```text
AnkiDroid Version = 2.18.2 (f624ca684f2bee10203c67ed4f801aa4c5423b95)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A415F

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A415F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36

ACRA UUID = e9d89abd-dd5f-453c-a0d8-162ebfbf818e

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Fixed in #16530

Should be in 2.18.4

**Comment by iagann** [comment]
Problem persists after the 2.18.4 update. Moreover, the old solution of adding preload="auto" doesn't work anymore

**Comment by david-allison** [comment]
2.18.4 hasn't been released, could you provide debug info

**Comment by iagann** [comment]
Sorry, it's 2.18.3

AnkiDroid Version = 2.18.3 (e74513bdd21d521a7939a8b1f781123fb3ee2025)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A415F

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A415F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = e9d89abd-dd5f-453c-a0d8-162ebfbf818e

FSRS Enabled = false

Crash Reports Enabled = true

**Comment by iagann** [comment]
Fixed in 2.18.4
Thanks!
