### ISSUE TITLE
MultimediaActivity: Canvas: trying to draw too large(192000000bytes) bitmap

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17378]
https://ankidroid.org/acra/app/1/bug/254079/report/8394c29e-bae5-4c6a-9684-09600daff226

```
java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.widget.ImageView.onDraw(ImageView.java:1449)
	at android.view.View.draw(View.java:23351)
	at android.view.View.updateDisplayListIfDirty(View.java:22210)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:23356)
	at android.view.View.updateDisplayListIfDirty(View.java:22210)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:232)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:222)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:22199)
	at android.view.View.draw(View.java:23076)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4544)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:23356)
	at com.android.internal.policy.DecorView.draw(DecorView.java:896)
	at android.view.View.updateDisplayListIfDirty(View.java:22210)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4924)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4625)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3813)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2543)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9465)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8289)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by david-allison** [comment]
@criticalAY FYI

**Comment by criticalAY** [comment]
`ImageView` related issue, the code is being migrated to webview we can wait for the next release after 
- #17035

is merged this should be fixed hopefully

**Comment by mikehardy** [comment]
I posted a PR that actually fixes this, using WebView does not really fix it (noted same in that PR, with repro)

**Comment by david-allison** [comment]
May be relevant: the problem is the **uncompressed** size as a bitmap [width * height * bit depth], not necessarily the size of the image itself, which may be below the AnkiWeb limit.

Similar issue:

https://github.com/ankidroid/Anki-Android/blob/5904c8a2119351c1e7d93dbd73ab88577a27ca30/AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt#L75-L97
