### ISSUE TITLE
Add 'Help' icon for sync conflict

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17544]
This is a major point of confusion for users, and could be massively improved with a help icon

![Image](https://github.com/user-attachments/assets/69e87e44-a376-4b0c-886e-31d4c90081e3)

Ref: https://www.reddit.com/r/Anki/comments/1h69d98/ankidroid_sync_success/

**Needs**

1) Figure out a good page to link to
    * Hopefully something in the Anki Manual/FAQ on sync conflicts 

2) Update the code in the following PR, so we can have all 3 of:
    * A dialog icon
    * A title
    * A 'help' icon

* https://github.com/ankidroid/Anki-Android/pull/17532

The help icon should look like this:

![Image](https://github.com/user-attachments/assets/c815c455-d214-49c0-ac00-fd82a2dc8728)

**Comment by Giyutomioka-SS** [comment]
working on this!

**Comment by brishtibheja** [comment]
This is the best topic to link to if you want Anki Manual: https://docs.ankiweb.net/syncing.html#conflicts

Uses desktop specific terms (for now).

**Comment by david-allison** [comment]
We probably want our own, given the dialog is different

**Comment by Aditya13s** [comment]
@Giyutomioka-SS Are you working on this? If not, can I?

**Comment by Giyutomioka-SS** [comment]
> [@Giyutomioka-SS](https://github.com/Giyutomioka-SS) Are you working on this? If not, can I?

Yes, i m working.

**Comment by snowtimeglass** [comment]
> The link location also needs to be improved to be AnkiDroid specific

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/17580#issuecomment-2529356893_
            

What do you think about the idea of opening an additional dialog box or an in-app page?

(The mental load may be high for common users to open a page outside the app, and especially for non-native English users to read the contents even if they can use automatic translation.)

**Comment by david-allison** [comment]
@snowtimeglass Yes, once we figure out the messaging which we want.

I suspect there's going to be a lot of discussion over the best way to phrase this, and I don't want to burden translators with work which will be wasted

**Comment by arman9919** [comment]
Looking into it.

**Comment by Shukla007** [comment]
I would be happy to work on this issue if no one else is.

**Comment by Haz3-jolt** [comment]
> I would be happy to work on this issue if no one else is.

Hey! the fix for this is quite simple, issue is the exact phrasing and deciding with webpage link vs dialog. If you have a solution, discuss it here before picking it up, since your solution might not be accepted at a later point.

**Comment by sakesane** [comment]
Hi @david-allison , I’d like to take on this issue (#17544) and propose the following approach, which aims to address the concerns raised in the discussion:

UI Structure:
A dialog icon as it originally has on the left of title,
A title,
A help icon, consistent with the pattern in PR #17532.
Help Behavior:
Tapping the help icon will open a simple in-app dialog. This dialog will contain:
A concise, AnkiDroid-specific explanation of what a sync conflict is and how to resolve it.
A link to the official manual (https://docs.ankiweb.net/syncing.html#conflicts) at the bottom.
Example draft wording (to be refined with feedback):
“A sync conflict occurs when you’ve made different changes to the same card on multiple devices. Anki can’t merge these automatically, so you must choose whether to keep the version from this device (Upload) or from AnkiWeb (Download). If you’re unsure, choosing Download is usually safer.” 

If this direction looks good, I’ll prepare a PR. Happy to iterate on the wording or UI based on your feedback!

**Comment by david-allison** [comment]
Sounds good to start.

Look into what Anki Desktop does. I feel just adding the icon and linking to the web page would be sufficient to close this.

**Comment by sakesane** [comment]
@david-allison thanks for your reply. 
I’ve tested Anki Desktop — its sync dialog has no clickable help icon (see screenshot).

<img width="627" height="294" alt="Image" src="https://github.com/user-attachments/assets/8b46cafb-1669-45df-a1a4-54a1384f5228" />

My proposed solution:
1. Keep the existing dialog icon.
2. Add a clickable help icon (?) that links to the web page.

Should I change ankidroid's dialog text according to the desktop version (which is more clear i think)?

**Comment by ZornHadNoChoice** [comment]
> A sync conflict occurs when you’ve made different changes to the same card on multiple devices.

I don't think the user needs to know this, and is it even accurate? What about the "full upload of the database" or the "one way sync"?

> If you’re unsure, choosing Download is usually safer.

Is it? I bet some users wil be angry after pressing "Download" (and losing progress) blaming the dialog.

I personally think a visual approach would be better, something like this (maybe with icons instead of text):

![Image](https://github.com/user-attachments/assets/850e3bc4-09a7-44eb-bc06-5dac8392a243)

**Comment by Haz3-jolt** [comment]
> I personally think a visual approach would be better, something like this (maybe with icons instead of text):

I disagree, visual approaches often create more confusion and aren't friendly to those who use screen readers or other accessibility measures.

**Comment by sakesane** [comment]
@ZornHadNoChoice Thank you for the correction, I'm a beginner so there may be quite a few mistakes.
Do you think it would be better to copy the dialog text from anki desktop to ankidroid, or should I just keep the ankidroid sync dialog text as it is?
Also, would changing text cause unecessary extra work for translators?
If it's more trouble than it's worth, maybe we should just add the icons&links and leave the text untouched, just as david-allison suggested..

**Comment by ZornHadNoChoice** [comment]
> I disagree, visual approaches often create more confusion and aren't friendly to those who use screen readers or other accessibility measures.

There can still be text, but the buttons would be under the diagrams representing their function.

> Do you think it would be better to copy the dialog text from anki desktop to ankidroid, or should I just keep the ankidroid sync dialog text as it is?

The Anki Desktop dialog is clearer in my opinion.

> Also, would changing text cause unecessary extra work for translators?

I personally wouldn't mind (as long as it's on Cowdin instead of Pontoon), but I can't speak for other translators.

**Comment by david-allison** [comment]
I feel discussions on the dialog content should be moved to another issue so we can move forwards with this

* EDIT: https://github.com/ankidroid/Anki-Android/issues/19340

For now:

* https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency Improve our conflict page  https://github.com/ankidroid/ankidroiddocs/issues/166  
  * https://docs.ankidroid.org/#AnkiWebConflicts 
  * This should be a very quick change to approve, if anything is required.
* Add the help icon + link the above page

----

**Context: Current Dialog Strings**

We took the current string based on feedback from a UX designer, but I feel we can do better, both with visuals, potentially exposing more data from the AnkiWeb collection (`mod`?), and closer text to Anki Desktop, if not matching it.

**Comment by sakesane** [comment]
@david-allison Since the dependency blocking this issue is fixed, would it be ok that I move forward with this issue? If so, I will keep the existing dialog content and add the help icon & the link.

**Comment by david-allison** [comment]
Sounds good, cheers!

**Comment by Abhishekkange** [comment]
Hi @david-allison , I’ve checked the latest build and confirmed the help buttons are still missing. I would like to work on this issue.

I think we can implement your first suggestion of adding a help icon and when it is click we can show another popup or dialogue box with the required information to the user (instead of navigating him to a blog page)

**Comment by david-allison** [comment]
@Abhishekkange sure!

See this for a starting point, we might just be able to use it.

https://github.com/ankidroid/Anki-Android/blob/f5739362f0f38c46157566fbae23002a92011ae7/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt#L437-L441

**Comment by Alok-Silswal** [comment]
Hi @david-allison,

I’ve gone through the issue and the related discussions, and based on the discussion so far, I’d like to propose a concrete way to implement this.

We could add a help icon that opens a short dialog explaining the sync conflict clearly, with a link to the blog/manual at the end for users who want more detail. The dialog can be dismissed by tapping outside, returning the user to the sync conflict dialog once things are clear.

Visual flow:
Sync conflict dialog → Help icon → Explanation dialog → tap outside → back to sync conflict dialog

If this approach aligns with what you had in mind earlier, I’d be happy to work on implementing it.

**Comment by david-allison** [comment]
Just use `titleWithHelpIcon` with a link to the Anki Desktop manual page, unless there's a reason to complicate it

**Comment by Fandroid745** [comment]
I am working on this now.

**Comment by siddhesh-06** [comment]
Hello @david-allison , I went through the discussion and the related PRs. May I work on this issue?

**Comment by david-allison** [comment]
This is still assigned, and In progress. I had a small chat about it recently: 

https://discord.com/channels/368267295601983490/701922522836369498/1466839253354020886

**Comment by Fandroid745** [comment]
The select collection to keep(title-text) autosizes to two lines after the addition of the help icon on the right  when the text apperance attribute is set to textAppearanceHeadlineSmall due to less available width for text. We allow this to happen when we override onMeasure:
https://github.com/ankidroid/Anki-Android/blob/bc78d4a123e7ec999a7e575570a7e2e9c6cd1217/AnkiDroid/src/main/java/com/ichi2/anki/workarounds/DialogTitleView.kt#L77C1-L78C1
This leads to an increased title height compared to the original dialog.

**Comment by david-allison** [comment]
I was in this area yesterday: https://github.com/ankidroid/Anki-Android/pull/20273

<details>

<summary>this patch which disables `DialogTitleView`</summary>

```patch
Index: AnkiDroid/src/main/res/xml/preferences_developer_options.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/xml/preferences_developer_options.xml b/AnkiDroid/src/main/res/xml/preferences_developer_options.xml
--- a/AnkiDroid/src/main/res/xml/preferences_developer_options.xml	(revision 7bc8ff558e6e3392da5a5c7c65b14373cf521083)
+++ b/AnkiDroid/src/main/res/xml/preferences_developer_options.xml	(date 1769928042786)
@@ -22,6 +22,12 @@
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:title="@string/pref_cat_dev_options"
     android:key="@string/pref_developer_options_screen_key">
+    <Preference
+        android:title="Dialog"
+        android:key="@string/dev_a"/>
+     <Preference
+        android:title="Material Dialog"
+        android:key="@string/dev_b"/>
     <SwitchPreferenceCompat
         android:title="@string/dev_options_enabled_pref"
         android:key="@string/developer_options_enabled_by_user_key"
Index: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/DialogTitleView.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/workarounds/DialogTitleView.kt b/AnkiDroid/src/main/java/com/ichi2/anki/workarounds/DialogTitleView.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/workarounds/DialogTitleView.kt	(revision 7bc8ff558e6e3392da5a5c7c65b14373cf521083)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/workarounds/DialogTitleView.kt	(date 1769928251508)
@@ -66,29 +66,6 @@
     ) {
         super.onMeasure(widthMeasureSpec, heightMeasureSpec)
 
-        val layout = layout ?: return
-        val lineCount = layout.lineCount
-        if (lineCount <= 0) return
-
-        val ellipsisCount = layout.getEllipsisCount(lineCount - 1)
-        if (ellipsisCount == 0) return
-
-        setSingleLine(false)
-        setMaxLines(2)
-
-        context.withStyledAttributes(
-            null,
-            R.styleable.TextAppearance,
-            android.R.attr.textAppearanceMedium,
-            android.R.style.TextAppearance_Medium,
-        ) {
-            val textSize = getDimensionPixelSize(R.styleable.TextAppearance_android_textSize, 0)
-            if (textSize != 0) {
-                // textSize is already expressed in pixels
-                setTextSize(TypedValue.COMPLEX_UNIT_PX, textSize.toFloat())
-            }
-        }
-
-        super.onMeasure(widthMeasureSpec, heightMeasureSpec)
+        TODO()
     }
 }
Index: AnkiDroid/src/main/res/values/preferences.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/preferences.xml b/AnkiDroid/src/main/res/values/preferences.xml
--- a/AnkiDroid/src/main/res/values/preferences.xml	(revision 7bc8ff558e6e3392da5a5c7c65b14373cf521083)
+++ b/AnkiDroid/src/main/res/values/preferences.xml	(date 1769928011176)
@@ -234,6 +234,8 @@
     <string name="dev_card_browser_fragmented">cardBrowserFragmented</string>
     <string name="dev_card_browser_search_view">cardBrowserSearchView</string>
     <string name="dev_open_tts_voices">openTtsVoices</string>
+    <string name="dev_a">a</string>
+    <string name="dev_b">b</string>
     <!-- Developer options > Create fake notes -->
     <string name="pref_fill_default_deck_number_key">FillDefaultNumberDeck</string>
     <string name="pref_fill_default_deck_key">FillDefaultDeck</string>
Index: AnkiDroid/src/main/java/com/ichi2/anki/preferences/DeveloperOptionsFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DeveloperOptionsFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DeveloperOptionsFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DeveloperOptionsFragment.kt	(revision 7bc8ff558e6e3392da5a5c7c65b14373cf521083)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DeveloperOptionsFragment.kt	(date 1769928108202)
@@ -20,6 +20,7 @@
 import androidx.core.content.edit
 import androidx.preference.Preference
 import androidx.preference.SwitchPreferenceCompat
+import com.google.android.material.dialog.MaterialAlertDialogBuilder
 import com.ichi2.anki.AnkiDroidApp
 import com.ichi2.anki.BuildConfig
 import com.ichi2.anki.CollectionHelper
@@ -192,6 +193,25 @@
             true
         }
 
+        requirePreference<Preference>(R.string.dev_a).setOnPreferenceClickListener {
+            MaterialAlertDialogBuilder(requireContext()).show {
+                setTitle("One two three four five six seven eight nine ten eleven")
+                setMessage("b")
+            }
+            Timber.w("b")
+            true
+        }
+
+        requirePreference<Preference>(R.string.dev_b).setOnPreferenceClickListener {
+            MaterialAlertDialogBuilder(requireContext()).show {
+                setTitle("One two three four five six")
+                setMessage("b")
+            }
+            Timber.w("b")
+            true
+        }
+
+
         setupWebDebugPreference()
     }
```

</details>

produces:

<img width="584" height="140" alt="Image" src="https://github.com/user-attachments/assets/63d76509-b364-43bd-a579-7c2729594d0d" />
<img width="557" height="148" alt="Image" src="https://github.com/user-attachments/assets/7a423036-3297-4318-9403-a28e6c176768" />

**Comment by Fandroid745** [comment]
I applied the patch you shared and ran the app.
This is how the dialogs are being displayed on my phone:

Dialog:
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/c87fd0e1-8abe-4da5-8e39-58442599b2d2" />

Material Dialog:
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/cbfbaee9-adf7-401c-b572-642fff50c202" />

**Comment by david-allison** [comment]
Hmm... that's unusual. Do you know why?

**Comment by Fandroid745** [comment]
I am unsure why it is happening on my phone but not for you. When I check https://android.googlesource.com/platform/frameworks/base/+/de47f1c358c8186ff3e14b887d5869f69b9a9d6c/core/java/com/android/internal/widget/DialogTitle.java
Even dialog title allows 2 lines ,is it possible that the behavior is device specific?

**Comment by david-allison** [comment]
Potentially. What's your debug info?

**Comment by Fandroid745** [comment]
AnkiDroid Version = 2.24.0alpha5-debug (280acf1882844d9beee789f8a08e0548465fdc00)  
Backend Version = 0.1.63-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = Xiaomi | Xiaomi | sweetin | aosp_sweet | M2101K6P | qcom  
WebView Info = [com.google.android.webview | 755905933]: Mozilla/5.0 (Linux; Android 15; M2101K6P Build/BP1A.250505.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/144.0.7559.59 Mobile Safari/537.36  
ACRA UUID = 4ee17ef4-8387-48a9-a8b9-ec13f70aa3f8  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = false
