### ISSUE TITLE
No confirmation dialog after editing the card browser appearance or deck override

### ISSUE THREAD

**Issue by ZornHadNoChoice** [ankidroid/Anki-Android#18518]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to manage note types.
2. Tap on edit cards on a note type.
3. Tap the 3 dot button.
4. Tap on card browser appearance and type something.
5. Alternatively, tap deck override and chose a deck.
6. Leave the note editor.

### Expected behaviour

A confirmation dialog shows up.

### Debug info

```text
AnkiDroid Version = 2.21alpha18 (5464fe94fefe937fd7eca143805eec18cecde9f3)
Backend Version = 0.1.52-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)
Android Version = 13 (SDK 33)
ProductFlavor = full
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.61 Mobile Safari/537.36
ACRA UUID = b9d03d9a-5af9-4e67-987e-cc15799171e2
FSRS = 2.0.3 (Enabled: true)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Edit: I noticed that the same is true for adding, renaming or deleting a card type (renaming card types doesn't trigger a confirmation dialog in Anki Desktop).

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ZornHadNoChoice** [comment]
Still exists in v2.23.0alpha4.

**Comment by sidharth6761** [comment]
Hey @david-allison can i contribute to this issue?

**Comment by david-allison** [comment]
Sure, thanks!

**Comment by sidharth6761** [comment]
@david-allison i guess this issue is already resolved , kindly check once.

**Comment by david-allison** [comment]
It's not fixed

AnkiDroid Version = 2.23.0alpha0-debug (a1c980b00bb2a36cfd2c8618a3caf983006d5068)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 16 (SDK 36)  
ProductFlavor = full  
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman  
Webview User Agent = Mozilla/5.0 (Linux; Android 16; Pixel 9 Pro Build/BP3A.250905.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.155 Mobile Safari/537.36  
ACRA UUID = f15ede14-140e-4890-bb11-8f07bdb64a05  
FSRS = 4.1.1 (Enabled: true)  
Crash Reports Enabled = false

**Comment by ZornHadNoChoice** [comment]
You need to press the back arrow button or your systems method of navigating back.

**Comment by sidharth6761** [comment]
@ZornHadNoChoice Kindly share a screen recording of the issue for better resolvment.

**Comment by ZornHadNoChoice** [comment]
https://github.com/user-attachments/assets/ee1737a5-3893-4b74-8f2d-62e5b6ed4a2d

**Comment by sidharth6761** [comment]
@ZornHadNoChoice i see the issue now. Expected behaviour is that it should show a confirmation dialogue box to save the changes . Right?
kindly clarify if i have been mistaken .

**Comment by ZornHadNoChoice** [comment]
Yes. It should look like this:

![Image](https://github.com/user-attachments/assets/abd13005-ab6d-4b05-b391-2839f8fa0a6e)

**Comment by sidharth6761** [comment]
@david-allison i dont understand this is already there in the codebase when we navigate back from the editor , the confirmation box pops up but the application in playstore doesnt do so . Is the app not updated in the playstore? I went through the repo and everything seems fine . Please confirm 

https://github.com/user-attachments/assets/40813743-0d25-48f0-b089-9cae854fec00

**Comment by david-allison** [comment]
I'll confirm in the latest alpha, please ping me if I haven't responded within 3 hours

**Comment by sidharth6761** [comment]
@david-allison please confirm

**Comment by david-allison** [comment]
Still reproducible

**Comment by ShaanNarendran** [comment]
Hi, could I be assigned this issue?

**Comment by david-allison** [comment]
Hi, we're saving this one for a research study, so it shouldn't be worked on

**Comment by ShaanNarendran** [comment]
> Hi, we're saving this one for a research study, so it shouldn't be worked on

Ah ok, I had actually just added a line to the code which fixed the issue of the dialog box not showing up when a user does a deck override and tries to exit without saving it. As far as I saw in the newest version, the app just lets you exit the edit screen after doing the override but after that change the dialog box does show up. Should I post that change?

**Comment by david-allison** [comment]
With apologies, please don't. 

This one is my responsibility, and I profusely apologize for the overight.

We were contacted by a researcher from Stanford in late October regarding a study, and they requested a number of issues to be tagged for evaluation.

I didn't get around to marking these issues as 'assigned'

**Comment by david-allison** [comment]
This issue was not selected for research and is open to contributions.

**Comment by manocormen** [comment]
@david-allison Could I be assigned this? Cheers
