### ISSUE TITLE
"No such file or directory" after sync

### ISSUE THREAD

**Issue by sigkell** [ankidroid/Anki-Android#4197]
I added some LaTeX cards on my PC and synced it to AnkiWeb. When I synced it to AnkiDroid, I got an error dialog saying `java.util.zip.ZipException: no such file or directory`.

When I review the deck, the image isn't present on the card. It's just a blank placeholder.

**Comment by sigkell** [comment]
Also worth noting that I'm currently using the Android N preview, which most likely caused the issue. Still odd.

**Comment by hssm** [comment]
Thanks. I reproduced the error while syncing media on an Android N emulator.

**Comment by hssm** [comment]
I [submitted a bug report](https://code.google.com/p/android/issues/detail?id=206398) to the Android project about this issue.

For now you can disable media sync in the settings to avoid seeing the error and manually copy over media files from/into your `collection.media` directory.

**Comment by hssm** [comment]
Can you tell me what device you are running so I can include it in the bug report?

**Comment by sigkell** [comment]
Nexus 6P.

**Comment by hssm** [comment]
Fixed upstream in the next developer preview.

**Comment by sigkell** [comment]
Just an update, latest developer preview doesn't fix this. The bug report did say a "future" build though, so it might come next month.

**Comment by xandep** [comment]
I too have the `java.util.zip.ZipException: no such file or directory` error when trying to sync. Yes, it started happening after upgrading to **Android N Developer Preview 3** on a Nexus 5X. Ankidroid 2.5.4, also reinstalled from scratch (deleting Ankidroid folders too), to no avail.

**Comment by hssm** [comment]
They've claimed to have fixed it for a second time, so we will see what happens when the next build is out. I'll leave this issue open until then so people can find it easily.

**Comment by rajasiman** [comment]
Hey there.

I've updated the application to the latest version (2.6) and still see this error.

| Details | |
| :--- | :--- |
| **Device** | Google Pixel C |
| **Android Version** | Android N Preview Beta 3 (NPD35K) |

| Permissions Granted | |
| :--- | :--- |
| Microphone | Yes |
| Storage | Yes |
| Read and write to the Ankidroid database |Yes |

I have tried clearing all permissions and start the application so that permissions are requested from within the application. Only the storage permissions were requested. Also, granted all 3 permissions, but this still continues to happen. Screenshot available [here](https://i.imgur.com/45tVzQ3.png). (unable to upload to github due to some unknown reason.)

Cheers!

**Comment by sigkell** [comment]
Issue still exists on DP4 (released last night).

**Comment by hssm** [comment]
They said the fix isn't in DP4 yet so we just have to wait. I'm not putting in a workaround for a bug in a preview build. I expect Google to fix their stuff.

**Comment by elnoxvie** [comment]
I understand this not the **AnkiDroid** issue but since i can't wait for the official Fix from google (I just don't know when they will release), i have made a temporary fix for this and made the Apk available (signed using Debug Key). (link)(https://github.com/elnoxvie/Anki-Android/releases). The source code for the changes is in the repo i forked. 

Hope it helps people who stumble onto this issue and can't wait for the official fix.

**Comment by tylerstraub** [comment]
Just came to add an additional report on the Android N preview (BUILD NPD56N) on a Nexus 6p

**java.util.zip.zipexception**

AnkiDroid Version = 2.6.1
Android Version = N
ACRA UUID = 1634dede-9371-4c13-a7b9-f371afff3be5

![ankidroid-java-util-exception error screenshot](https://cloud.githubusercontent.com/assets/4467134/16850622/de02a354-49b4-11e6-861d-2f5d2da82845.png)

Cheers!

**Comment by hssm** [comment]
The latest developer preview has fixed this issue.
