### ISSUE TITLE
AnkiDroid Directory not able to be accessed

### ISSUE THREAD

**Issue by RubLam** [ankidroid/Anki-Android#5097]
###### Reproduction Steps

1. Open AnkiDroid
2. Open advanced settings
3. Close advanced settings
4. That's it

When reinstalled it works perfectly fine and as soon as advance settings are opened it won't get access to the directory. 
I have tried moving the data around and adjusting the file path but it won't let me change it. 
If i try leaving the settings it either does nothing or closed the app. 

That's the video of what is happening: 
https://drive.google.com/file/d/1i_kQQniYP3Zn-TD-EhT6RS7cd6E1okMf/view?usp=drivesdk

###### Expected Result
Sorry i clearly don't know how this work just open the issues as asked. Hope i can help
Ask me for further details

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! I was the person that responded to your review - thanks for posting it here - I tried to access the video but it seems I need permission, I requested that - if I could see it happening it might help. Advanced preferences is an area of the app I was working on just today and it worked fine for me, so I have a feeling this is going to be a strange problem, whatever it is...

**Comment by mikehardy** [comment]
I'm posting it on youtube here so anyone can try to fix it: https://youtu.be/bCXlYpjcTdU

I'm unable to find your crash report, do you have the Android version of your device, and you're ACRA UUID? The instructions to get them are here: https://docs.ankidroid.org/help.html#_support

I understand that reproducing this issue causes your installation to be broken, which is frustrating I am sure. To get the debug info you will probably need to get the info after a fresh install, *then* trigger the issue (using the UUID you got earlier) then post the UUID here. The app generates a fresh UUID each install so if you crash, reinstall, then post the UUID they won't match up.

Thanks for the help trying to fix this

**Comment by RubLam** [comment]
These are the Debug Information matching a report I just did: 

AnkiDroid Version = 2.8.4

Android Version = 7.0

ACRA UUID = 8d369429-1de4-44e9-930e-9dc1d63da882

I hope that is helping. I'm glad if I can be if any help so feel free to ask for further information

**Comment by mikehardy** [comment]
Got the crash trace, thank you!

I'll need to look a little more deeply but this looks the same as #5074 which was just fixed, with the fix released in alpha versions that are already available.

But it should also only be happening if you hit the "force full sync" item just *below* the directory path configuration. And you're only being sent to this screen because it is not a valid directory path for some reason?

If you follow the instructions here to enable beta builds, then join the google alpha test group you should get the fresh build on your device after a bit less than a day more or less https://docs.ankidroid.org/#betaTesting

If you can still reproduce the crash then, that will be very unexpected, but also very useful to know

Whether it fixes the problem you are having accessing your collection, I don't know

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ichi2.libanki.Collection.modSchemaNoCheck()' on a null object reference
at com.ichi2.anki.Preferences$8.onPreferenceClick(Preferences.java:350)
at android.preference.Preference.performClick(Preference.java:1023)
at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:222)
at android.widget.AdapterView.performItemClick(AdapterView.java:313)
at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3195)
at android.widget.AbsListView$3.run(AbsListView.java:4138)
at android.os.Handler.handleCallback(Handler.java:761)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:199)
at android.app.ActivityThread.main(ActivityThread.java:6523)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by mikehardy** [comment]
I believe we have 3 reports of this now, all from users using a non-english language so it might be a localization issue

**Comment by RubLam** [comment]
Yeah the Problem is still occurring. 
But that seems promising. 

I didn't understand the Alpha group thing. I am a beta tester now but, I haven't found anything in the group yet, was I supposed to?

**Comment by mikehardy** [comment]
Once you have enabled betas in the play store for ankidroid then you join that google group for alphas and that's it. Some time later Google will start sending alpha versions, maybe a day after?

**Comment by RubLam** [comment]
Oh that's what I did but I didn't get any alphas in those 3 days

**Comment by mikehardy** [comment]
@RubLam that's weird - it should work! Can you see which version you have now? If it is 2.8.4, then signing up for the betas in the play store didn't work and you need to fix that. If it's 2.8.5-beta1 then signing up for betas worked, but you aren't correctly a member of the "alpha testers" google group I think. Or there's something we are missing entirely - like if you are on a very very old Android (older than 4.0.3) then the alphas are incompatible, Google Play won't serve them to you, and 2.8.4 the last version that will support it

**Comment by mikehardy** [comment]
Well, good news that the alpha was delivered, but that is terrible news for the problem you're having. You follow these instructions to leave the beta program: https://play.google.com/apps/testing/com.ichi2.anki so you can get the public v2.8.4 build that "only" stops you from using advanced preferences well.

I really appreciate the effort you've put in to testing this, I'll see what I can do to reproduce it locally.

For my own purposes, system locale is set to de_DE, it's Android 7 and on 2.8.4 we got the stack trace for the ACRA UUID above but for the alpha51 build there is no stack trace I can see.

**Comment by RubLam** [comment]
Yeah the alpha does run if I reinstall, but when the problem accures it doesn't open anymore so that there is also no crash report going out. 
Before the only way I got the app to send out such a report was by full force sync. I could try it immediately after the problem occurs.

**Comment by mikehardy** [comment]
Hmm - that force full sync report is unrelated I'm pretty sure - we did see the crash report but it's not the same problem - it was a separate problem that we have fixed in alpha now so you can't do a report that way. I am not sure if a report will give us much more information I just need to see if I can reproduce it locally with an emulator set up like your device

**Comment by mikehardy** [comment]
I looked into this today and was unable to produce the problem on an Android 7 emulator configured with de-DE as the language, on either the current alphas or the 2.8.x stable branch.

I understand this problem is deeply frustrating but I can't help until it is reproducible. if anyone that experiences this issue is able to send[ the logcat from their device](https://www.google.com.ec/search?q=get+logcat+from+android+device) while they reproduce it, or can give me a tap by tap scenario on an android emulator that reproduces it, that would potentially help.

Until then unfortunately I'll have to mark this waiting for feedback

**Comment by mghoug** [comment]
Le probleme arrive par exmple quand l'utilisateur a installé l'application ANKIdroid sur une carte SD externe

Lorsque le user entre dans le menu "Aavancé" des parametres, la variable contenant le chemin vers le répertoire d'installation est hélas réinitialisée !

Pour info, chez moi, le chemin vers le répertoire d'installation (sur la carte SD externe) est :
/storage/0000-0000/AnkiDroid
et si je le copnnecte par usb, le dossier est accessible depuis mon PC sous linux, par le protocole MTP, et le point de montage suivant:

mtp://[usb:002,004]/Carte SD/AnkiDroid

Pour résoudre le bug, il suffirait de conserver dans une variable le BON chemin vers le répertoire d'installation de AnkiDroid, puisque l'appli fionctionnait AVANT que l'utilisateur se retrouve dans ce menu parametre "AVANCé"
-> NE PAS MODIFIER CETTE VARIABLE
Et en cas de bug, réinitialiser le chemin à l'aide de cette variable pour rétablir les choses

Solution temporaire en attenda,t:
Interdire l'entrée dans ce menu "avancé", d'où on ne peut plus sortir...

**Comment by Arekkkk** [comment]
I got another issue with Ankidroid home directory.
I made a factory reset of my Phone (HTC E8) and, after resetting and reinstalling, it doesn't even manage to start properly, shouting that "AnkiDroid directory is inaccessible" (by default it is /sdcard/Ankidroid).
I tried to change the folder, but whatever destination I tap in, I get the message ""the path specified wasn't a valid directory" and the path remains without changes (/sdcard/Ankidroid)
I cannot use the app at all now - I resetted the phone again, once using the Options Menu, once using twrp, still the same problem.
What can I do...?   :''|

**Comment by mikehardy** [comment]
@Arekkkk This is still an ongoing problem but we're not sure how to reproduce it yet, I'm sorry it's blocking your review.

Maybe one of the techniques for external storage (unsupported, but with reports of success) could work? https://groups.google.com/forum/#!topic/anki-android/Eu7AXSQa6Es

Are you absolutely certain AnkiDroid is listed as having external storage permissions?

**Comment by Arekkkk** [comment]
mikehardy - the point is not that I cannot store my collection on the SD card. It it thet I cannot store it internally, either :(
No matter what access path I input, it says it's inaccessible...

**Comment by mikehardy** [comment]
Permissions maybe? Revoke and regrant permissions? If you are familiar with TWRP maybe you can help with a logcat capture filtered by anki? I can generate test builds with more information as needed if you can help nail this one... We haven't been able to get a logcat yet

**Comment by Arekkkk** [comment]
I also think it is sth with permissions...
I cant even make a screenshot, as it claims its got no permissions.
Probably sth got corrupted after that reset, so rather phone problem, than Anki problem, apparently.
I should thereby start looking for android support, not molesting you here - sorry for that and thanks for prompt answers.
Just need to find out how to address the backlog issue, as most probably it wont be solved soon. Unloading it using the web interface is such a pain...

**Comment by anki0208666** [comment]
I have the same problem. I'm using the German version (can I just somehow get it to install English instead?). 
I tried deinstalling and reinstalling and also removing and re-granting permissions.

**Comment by mikehardy** [comment]
@anki0208666  Have you tried using the internal name for the storage as opposed to the /sdcard alias? would be something like /storage/XXXX-XXXX/Ankidroid

There is no way to get the non-System language during installation, that I know of

**Comment by mikehardy** [comment]
@david-allison-1 I forgot about this one if you have time, it haunts so many people

**Comment by mikehardy** [comment]
Mostly these reports come from play store reviews like so 
![Screenshot_20200316-182809](https://user-images.githubusercontent.com/782704/76807940-19a15880-67b4-11ea-89a1-f27f656bc255.jpg)

**Comment by david-allison-1** [comment]
@mikehardy Sure.

If ACRA contains logcat, could you grep it for:

`Could not initialize directory`

**Comment by david-allison-1** [comment]
I don't have an SD card to verify the following right now. I'll see if I can do something about it in the next few days, but I'm probably not the best for the job.

My theory: This is a "Disk Full" error. The internal storage is full, so the APK is installed on external storage (as is allowed in the manifest).

https://github.com/ankidroid/Anki-Android/blob/55772d08ff83a4f82c154c2bb9de52758773dcb4/AnkiDroid/src/main/AndroidManifest.xml#L24

https://developer.android.com/guide/topics/data/install-location.html

When the user opens settings, it tries the default location, can't write (as the disk is full) and goes into a crash loop.

**Comment by david-allison-1** [comment]
I'll say without testing that the above is the issue.

A combination of installing to external storage and #5346 (opening preferences sets the default values supplied in the XML, which doesn't go through our normal validation routine).

If the user has installed AnkiDroid on external media, then it's automatically selected.

https://github.com/ankidroid/Anki-Android/blob/646de8556ea28f178a4c7c8dbb8240622a7dbe80/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L188-L196

When the user enters preferences, they have "deckPath" set (likely by the framework, I'll check when I'm on my PC).

This overrides the default with a different, incorrect default.

https://github.com/ankidroid/Anki-Android/blob/646de8556ea28f178a4c7c8dbb8240622a7dbe80/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L138-L171

**Comment by tbop** [comment]
Hi,

I'm experiencing the same issue. I've just moved from a Samsung A5 (2016) where AnkiDroid's data was stored on an SD Card to a Google Pixel XL (1st Gen but with Android 10). The Pixel XL has no SD card. Yet I believe the app does refer to a valid path on the internal storage path but the app keeps saying that this directory is not valid.

I've already reinstalled the app twice, and of course checked that all the permissions are enabled already but no chance... The app only shows the Advance Preferences and there is no way to use my flash cards anymore.

Original message posted here: https://github.com/ankidroid/Anki-Android/issues/6345#issuecomment-753306997

Thank you so much for your help!
