### ISSUE TITLE
Card Preview unable to determine TTS language

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5138]
See more recent comments :point_down:  https://github.com/ankidroid/Anki-Android/issues/5138#issuecomment-598962085 as this issue is slightly different after one mitigation patch to stop it from crashing completely

---------

###### Reproduction Steps

1) during a review, select some text from the card
2) choose "card browser" in the now shown copy/paste menu
3) long-click any card in the browser and choose "preview"
4) go back to your reviews (Android back button)
5) after one or two new cards Ankidroid crashes

The last message I can see before the crash is "no voice for playback found" (in German, which is my interface language). Then the card fails to load (I'm using TTS) and Ankidroid crashes and restarts automatically

I can reproduce this bug with above steps at any time. So if you need more information about it, just tell me what to do.

###### Expected Result

No crash

###### Actual Result

Crash

###### Debug info

AnkiDroid Version = 2.9alpha52

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Just to let you know I have the stack of issues queued for review but I was focusing on the sizable changes that are the fix for #5011 and haven't had time for anything else. Hopefully in the next few days

**Comment by Anthropos888** [comment]
Still crashes with latest alpha:
AnkiDroid Version = 2.9alpha63

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

Before the crash a message was shown that a report was send to the developers. Maybe you can find out the reason of the crash with that report

**Comment by mikehardy** [comment]
The stack was this:

```
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:466)
at com.ichi2.anki.ReadText$2.run(ReadText.java:139)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Anthropos888** [comment]
Just as a short update: crash persists under Android 9 and 2.9alpha66:

AnkiDroid Version = 2.9alpha66

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

**Comment by mikehardy** [comment]
Same stack, this time I'm including the logcat as well (there is no PII / personally identifying information, no worries) as that shows some of the click sequence on the way to the crash in case it helps

Sorry I haven't had time yet - working like mad at the day job on the way to a pilot for our app's first launch. I'm still listening though...

```

03-23 10:04:21.164 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1543506956899
--
3 | 03-23 10:05:07.542 I/AnkiDroid( 9779): AbstractFlashcardViewer:: EASE_2 pressed
4 | 03-23 10:05:07.792 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1543506956597
5 | 03-23 10:06:12.764 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1519997986598
6 | 03-23 10:06:43.648 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1520863619664
7 | 03-23 10:08:07.957 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1509966041114
8 | 03-23 10:09:17.946 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1543506956397
9 | 03-23 10:10:16.440 I/AnkiDroid( 9779): Cancelled task 30
10 | 03-23 10:10:16.461 I/AnkiDroid( 9779): _findCardsForCardBrowser() cancelled...
11 | 03-23 10:10:16.685 I/AnkiDroid( 9779): CardBrowser:: Completed doInBackgroundSearchCards Successfully
12 | 03-23 10:10:17.040 I/AnkiDroid( 9779): flush - Saving information to DB...
13 | 03-23 10:10:59.273 I/AnkiDroid( 9779): onCollectionLoaded() Edit note activity successfully started with card id 1543506956529
14 | 03-23 10:11:33.465 I/AnkiDroid( 9779): Saving instance
15 | 03-23 10:11:53.177 I/AnkiDroid( 9779): NoteEditor:: Home button pressed
16 | 03-23 10:11:53.213 I/AnkiDroid( 9779): Creating notification channel with id/name: General Notifications/AnkiDroid
17 | 03-23 10:11:53.216 I/AnkiDroid( 9779): Creating notification channel with id/name: Synchronization/Synchronisierung
18 | 03-23 10:11:53.227 I/AnkiDroid( 9779): Creating notification channel with id/name: Global Reminders/Fällige Karten
19 | 03-23 10:11:53.229 I/AnkiDroid( 9779): Creating notification channel with id/name: Deck Reminders/Erinnerungen
20 | 03-23 10:12:01.091 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1543506956529
21 | 03-23 10:12:28.650 I/AnkiDroid( 9779): Back key pressed
22 | 03-23 10:12:30.944 I/AnkiDroid( 9779): Back key pressed
23 | 03-23 10:12:57.009 I/AnkiDroid( 9779): AbstractFlashcardViewer:: EASE_2 pressed
24 | 03-23 10:12:57.136 I/AnkiDroid( 9779): AbstractFlashcardViewer:: Question successfully shown for card id 1543506956503
--------- beginning of crash




```

**Comment by mikehardy** [comment]
I was reading some lifecycle architecture notes unrelated to this but happened on this snippet here https://developer.android.com/topic/libraries/architecture/lifecycle#java

> A common use case is to avoid invoking certain callbacks if the Lifecycle isn't in a good state right now. For example, if the callback runs a fragment transaction after the activity state is saved, it would trigger a crash, so we would never want to invoke that callback.

Seems like this is a lifecycle-related crash so this might be the direction for the fix

**Comment by Anthropos888** [comment]
Still crashes in 2.9beta5

Although the issue https://github.com/ankidroid/Anki-Android/issues/5251
was solved before doesn't crash anymore, this one here seems to have a different cause.

**Comment by mikehardy** [comment]
#5804 should fix this and will be in the 2.10alpha46 and higher

**Comment by Anthropos888** [comment]
Since alpha46 it doesn't crash anymore after preview. But an error message is shown "no tts language available..." and the TTS indeed stops working during reviews. The only way to get TTS working again is to return to the deck list and start a new review session.

**Comment by mikehardy** [comment]
Great news it is no longer crashing! Not sure what we can do about the TTS not working afterwards, the crash was that it was trying to show the dialog to pick the language for the deck, because it determined there was no language selected. That's happening here for some reason: https://github.com/ankidroid/Anki-Android/pull/5804/files#diff-c97beb080b02dc39a424b249bdf343dbL215

Odd one. I'll re-open it but alter the description / text

**Comment by Anthropos888** [comment]
![Screenshot_20200314-091947~(1)](https://user-images.githubusercontent.com/45192213/76678089-4a776700-65d5-11ea-8949-abb9480de464.jpg)

That's the message that is shown during reviews (after previewing a card in the card browser)

**Comment by mikehardy** [comment]
@Anthropos888 can I make the bold assumption that language tag 'ja' does in fact have an installed TTS language and should be working on your system? Thanks for the extra feedback

**Comment by Anthropos888** [comment]
@mikehardy That's correct. JA and other TTS languages are installed and working normally until this bug occurs.

**Comment by Anthropos888** [comment]
Bug still occurs as of 2.10alpha12.
BTW it's not limited to JA language, the message "No text-to-speech language available (EN-GB)" also occurs in my English deck after browser preview.

**Comment by david-allison-1** [comment]
@Anthropos888 I've tried to reproduce this just now and it worked fine :/. I think this will be gated on getting better debug feedback (probably #6264). 

P.S: Pretty sure that's 2.11alpha12

**Comment by Anthropos888** [comment]
2.11alpha12, sorry. 
Did you do the following?
1) review a simple card that uses TTS (language doesn't matter)
2) select the word in the front
3) choose "card browser" from the floating menu
4) long tap the first result in card browser -> preview
5) preview the front and back of that card (note: the TTS still works in this preview)
6) go back to reviews with your phone's back button
7) press show answer (note: this won't work with swipe gesture on my phone, instead it goes straight to the next card. So I go back manually to the previous card and swipe again to shown answer)
8) the TTS error message occurs

**Comment by mikehardy** [comment]
I reproduced this at some point, I do remember that

**Comment by Anthropos888** [comment]
I just noticed the new "eye" icon in the edit note screen. That means, the TTS bug is now reproducable even faster:

1) review a card with TTS
2) choose "edit note" from the menu
3) tap the eye icon to preview the card
4) press your phone's back button twice to return to the reviewer => error message occurs and TTS fails to speak

**Comment by mikehardy** [comment]
but previewing from note editor is so sweet, otherwise right? ;-)
reproducing bugs more quickly is just a nice (i suppose) side effect)

**Comment by Anthropos888** [comment]
Ha ha yes, it's a really useful feature. Nice work!

**Comment by Anthropos888** [comment]
Bug still happens in AnkiDroid Version = 2.13alpha15

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

Scheduler = std2
