### ISSUE TITLE
Stuck at "1 day" intervals for v2 answer options

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#5229]
Since switching to v2, the three "remembered" intervals offered by AnkiDroid (b61) for any card I forgot since the transition all seem to be stuck on "1 day". (Apart from the "10 min" for "forgotten", which then changes the "hard" interval to "15 min" when it comes again as hot card.)

![screenshot](https://user-images.githubusercontent.com/887320/52521338-2df05900-2c76-11e9-8f7e-63e65fe094a9.png)

Interval factor in the deck options remains at 100%.

Since I don't use Anki Desktop for reviewing, I don't know if/how this relates to the half dozen or so commits it got to its v2 over the past days (apparently for bugs grave enough to require a 'reset' with [2.1.9](https://apps.ankiweb.net/docs/beta.html)), but right now the same card shown with "broken" intervals in AnkiDroid is indeed offered with the customary 10min-1d-2d-4d ones in Anki Desktop (5632ba).

**Comment by timrae** [comment]
@hssm

**Comment by timrae** [comment]
Try alpha62

**Comment by rathsky** [comment]
Bug remains. See this renamed apkg with a single note from today that exhibits it (dunno why the archive is so large): [Default.zip](https://github.com/ankidroid/Anki-Android/files/2847943/Default.zip)

Had to export it with AnkiDroid as Anki Desktop for whatever reason refuses to export _"single deck .apkg with [v2] scheduling"_ and asks to _"switch to the regular scheduler before exporting"_. (Which I guess implies the apkg might actually be corrupt.)

**Comment by rathsky** [comment]
Fixed with the new alpha.

**Comment by dejiapps** [comment]
I'm still having issue with the V2 scheduler. If I get a question wrong and choose again, good and easy get stuck at 1 day.
Are there special steps to take when going to the experimental scheduler that I should be aware of?

![Screenshot_AnkiDroid_20190403-180317](https://user-images.githubusercontent.com/21183832/55523407-09ea3c00-5657-11e9-8fc6-c05a68612efd.png)
 I'm using Version 2.1.11 on my mac and 2.9alpha67 of ankidroid.

**Comment by davidson16807** [comment]
This bug occurs for me as well, however for me no matter what button I press to rate the answer it says the next due date will be updated to "1 day". From what I can tell the application is correct in its statement, the next due date really does seem to update to this interval. 

This issue occurs on both of the machines I'm using. The first machine is version 2.1.54 running on Ubuntu 22.04.1 LTS with QT 5.15.3. The second machine is running the latest version for Android.

The issue only occurs on some decks. It appears the problematic decks are the ones I'm actively learning and have used in the past few days. I suspect the Ubuntu version of Anki might have ruined something in the database while synchronizing.  I had to update Ubuntu recently, 22.04 forces you to go through the snap store to get anything installed and the version of Anki that's out there there seems really flakey.
