### ISSUE TITLE
Audio not playing bug v 2.10

### ISSUE THREAD

**Issue by HaiMaiNameIsAni** [ankidroid/Anki-Android#6172]
###### Reproduction Steps

1. Card came up that had audio attached but no audio played.
2. I clicked on the play symbol but no audio came up, many of my cards lost audio, but a few still have them.
3. I checked all my decks, and this only seems to be happening with decks I made myself.

###### Expected Result
I expected the audio to play, or for it to at least play when I clicked the play button.

###### Actual Result
No audio played.
The text for the audio was still in the card, and a play symbol still showed, but the audio didn't play.

###### Debug info
.AnkiDroid Version = 2.10

Android Version = 9

ACRA UUID = e6f97ab7-b158-454c-abd6-e93bf5a37868

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @HaiMaiNameIsAni,

Thanks for the report, and sorry for the inconvenience.

I can't reproduce the issue with the information provided.

Could you either:

* Provide the HTML of the card, the sample audio, and the template in a form that someone could follow the instructions and reproduce the bug
* Provide us with your collection (with media and without scheduling information).
  * Either posting publicly, or sending me a private link via my gmail: davidallisongithub

All the best,

David

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

**Comment by StickerZhang** [comment]
Hi,
I also encountered this issue with v 2.10.2 on my Android 10 phone, the audio can be played in Anki Windows, but not worked on Ankidroid. 
Below is the codes of playing audio:

```
<audio
src="http://dict.youdao.com/dictvoice?audio={{Front}}&type=1"
controls=controls>
</audio>
<div>
```
And the collection attached:
[000 - Inbox.zip](https://github.com/ankidroid/Anki-Android/files/4655092/000.-.Inbox.zip)

I tried it with v 2.11 alph5, not work either...
Finally, I downgraded to v 2.9.7, the audio of all cards can be played on my phone then.

**Comment by david-allison-1** [comment]
Hi @StickerZhang, 

The fix is listed in the above link

> If the files are loaded from the internet over `http`, load them via `https` URLs. If HTTPS is not available, you can automatically convert these links to local files via an Anki Desktop Addon: https://ankiweb.net/shared/info/1293255374

All the best, 
David

**Comment by mikehardy** [comment]
Worth noting that every subsequent release of Chrome (that our webview is based one) tightens rules further, restricting usage of http further - so I recognize this is generating some frustration in users and some support load but moving to https is where things are going. The only compromise I could see making is maybe a toast or something if the card had an http URL in it.
But really, referencing a speech generator across the internet during review? That is not the way Anki is supposed to work - it destroys offline capability and stresses youdao. Media should be in collections

**Comment by Khater97** [comment]
Hi
I have the same problem. It is weird because I was studying the decks and after 5 days all audios stops working I deleted and re install the app but its same nothing changed what can I do?

**Comment by david-allison-1** [comment]
Hi @Khater97,

Have you tried following the instructions: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

All the best.

David

**Comment by StickerZhang** [comment]
The issue was solved on v 2.10.2 after I changed http to HTTPS, thanks a lot!
And the reason I don't put the media in the collections directly is the size of the collections will be very large then the sync becomes a problem...

**Comment by Khater97** [comment]
Hi


I don't understand I was studying and then it suddenly stopped working.&nbsp;
I look on your link all is good. So i still don't know what to do more. I uninstall and re install the app.&nbsp;



---Original---

**Comment by david-allison-1** [comment]
> Hi I don't understand I was studying and then it suddenly stopped working.&nbsp; I look on your link all is good. So i still don't know what to do more. I uninstall and re install the app.&nbsp;

Could you provide us with both the field (`Edit Note`), and the card template (`Edit Note - Cards...`) of a note which is no longer working.

Thanks,

David

**Comment by mikehardy** [comment]
@StickerZhang I have decks with 20,000 cards, each with sound and media. Sync is only a second or so for me. The first sync, yes that was big. But after the initial transfer sync of even massive collections should be lightning quick.

**Comment by Khater97** [comment]
All the decks&nbsp;
The audios are not working for all



---Original---

**Comment by david-allison-1** [comment]
> All the decks&nbsp; The audios are not working for all

I can't help you if you don't provide the information that I ask for.

> Could you provide us with both the field (`Edit Note`), and the card template (`Edit Note - Cards...`) of a note which is no longer working.

**Comment by Khater97** [comment]
OK I hope this can help&nbsp;


Front template&nbsp;
<center&gt;<font size="+3"&gt;{{exemples}}</font&gt;<br&gt;{{Media_ch}}</center&gt;&nbsp;
Back template&nbsp;
{{FrontSide}}<hr id="answer"&gt;<center&gt;<font size="+3"&gt;{{sent_ch}}</font&gt;<br&gt;<br&gt;{{sent_eng}}<br&gt;<br&gt;<font size="+1"&gt;{{Media_ch}}{{Media_eng}}</font&gt;<br&gt;<br&gt;<br&gt;{{py}}<br&gt;<br&gt;<font size="+1"&gt;FR : {{char_fr}}</font&gt;<br&gt;<br&gt;<font size="+1"&gt;ENG : {{char_eng}}</font&gt;</center&gt;&nbsp;

---Original---

**Comment by david-allison-1** [comment]
> OK I hope this can help&nbsp; Front template&nbsp; <center&gt;<font size="+3"&gt;{{exemples}}</font&gt;<br&gt;{{Media_ch}}</center&gt;&nbsp; Back template&nbsp; {{FrontSide}}<hr id="answer"&gt;<center&gt;<font size="+3"&gt;{{sent_ch}}</font&gt;<br&gt;<br&gt;{{sent_eng}}<br&gt;<br&gt;<font size="+1"&gt;{{Media_ch}}{{Media_eng}}</font&gt;<br&gt;<br&gt;<br&gt;{{py}}<br&gt;<br&gt;<font size="+1"&gt;FR : {{char_fr}}</font&gt;<br&gt;<br&gt;<font size="+1"&gt;ENG : {{char_eng}}</font&gt;</center&gt;&nbsp;
> […](#)
> ---Original--- From: "david-allison-1"<notifications@github.com&gt; Date: Thu, May 21, 2020 21:40 PM To: "ankidroid/Anki-Android"<Anki-Android@noreply.github.com&gt;; Cc: "Mention"<mention@noreply.github.com&gt;;"Khater97"<848554930@qq.com&gt;; Subject: Re: [ankidroid/Anki-Android] Audio not playing bug v 2.10 (#6172) All the decks&nbsp; The audios are not working for all I can't help you if you don't provide the information that I ask for. Could you provide us with both the field (Edit Note), and the card template (Edit Note - Cards...) of a note which is no longer working. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks, and the HTML of a field which contains media?

**Comment by Khater97** [comment]
This? https://ankiweb.net/shared/info/267225552&nbsp;



---Original---

**Comment by david-allison-1** [comment]
> This? https://ankiweb.net/shared/info/267225552&nbsp;

Works for me. Could you load the javascript debugger: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection and see if you can diagnose the problem on your end.

**Comment by Khater97** [comment]
I only use anki droid app. How can I use the deblogger?&nbsp;



---Original---

**Comment by david-allison-1** [comment]
The above instructions are for AnkiDroid,

**Comment by Khater97** [comment]
OK I found where to enable reviews. But I don't understand how to review one card on the app and look for this too&nbsp;
&nbsp;/sdcard/AnkiDroid

I'm. Sorry its a little complex system&nbsp;

---Original---

**Comment by HaiMaiNameIsAni** [comment]
I fixed the issue. I synced then uninstalled. Then I went into my files and
deleted all the media. Then I reinstalled and synced. It took forever to
sync again since I have over 2000 cards with audio, but it's working again!

**Comment by david-allison-1** [comment]
> OK I found where to enable reviews. But I don't understand how to review one card on the app and look for this too&nbsp; &nbsp;/sdcard/AnkiDroid I'm. Sorry its a little complex system&nbsp;

Look on your Android filesystem for the folder.
