### ISSUE TITLE
Pre-ACRA crash - NullPointerException: AnkiDroidApp.getAppResources

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6266]
This seems to occur before ACRA is initialised. I wasn't aware that this was possible. Stack trace implies that `Application.onCreate` didn't execute as getAppResources failed

```
java.lang.NullPointerException: 
  at com.ichi2.anki.AnkiDroidApp.getAppResources (AnkiDroidApp.java:303)
  at com.ichi2.anki.dialogs.AsyncDialogFragment.res (AsyncDialogFragment.java:22)
  at com.ichi2.anki.dialogs.DatabaseErrorDialog.getTitle (DatabaseErrorDialog.java:330)
  at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog (DatabaseErrorDialog.java:61)
  at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog (DatabaseErrorDialog.java:20)
  at androidx.fragment.app.DialogFragment.onGetLayoutInflater (DialogFragment.java:380)
  at androidx.fragment.app.Fragment.performGetLayoutInflater (Fragment.java:1412)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:881)
  at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManagerImpl.java:1238)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:1303)
  at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange (FragmentManagerImpl.java:2659)
  at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManagerImpl.java:2613)
  at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:246)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:542)
  at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:210)
  at com.ichi2.anki.AnkiActivity.onStart (AnkiActivity.java:65)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1392)
  at android.app.Activity.performStart (Activity.java:7157)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:2943)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:180)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:165)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:142)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1814)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:280)
  at android.app.ActivityThread.main (ActivityThread.java:6706)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

**Comment by Arthus** [comment]
As for this and #5905 :
I found this issue on the ACRA tracker https://github.com/ACRA/acra/issues/410 
From the last comment I see, that in ACRA 4.8.6 the "ACRA.isACRASenderServiceProcess()" method was added and if I understand it correctly, that method might supersede the "if (sInstance != null && sInstance.getResources() == null)" block in AnkiDroidApp.onCreate() with a cleaner solution?

**Comment by david-allison-1** [comment]
Oooh... Thanks! Didn't know that at all.

I'm not totally sure if we want to remove it - `.getResources()` can return null for other reasons.

But: I think we can add it in as another condition

But: This might also be a fix for #5883

**Comment by david-allison-1** [comment]
Probably solved in #6275, awaiting verification.

**Comment by david-allison-1** [comment]
Haven't seen this come up again. Thanks @Arthus! Saved me loads of time on this one.

**Comment by Arthus** [comment]
You're welcome, but seems like it was lucky shot.

Because I still don't understand, why the check helped in the place, that you added it in. Was the Fragment, that caused the crash, created by the ACRA-instance of AnkiDroidApp? Because your patch doesn't help setting sInstance and it doesn't prevent accessing getAppResources(). So if the crash is caused by getAppResources returning null, hitting that condition should still be possible.

I'm also not sure, how that part of the code can actually be reached. For onCreate() to not immediately return, sInstance != null _and_ sInstance.getResources() !=null must be fullfilled, so getAppResources() should never return null in that case.

Or is this some strange case of interaction between the processes? Two AnkiDroidApp processes are created, the second ACRA process starts something (like a fragment), that uses the first process's getAppResources and when the first process dies, the second process tries to access the process, that is gone, and dies too?
