### ISSUE TITLE
"Collection not opened" - Deck With Invalid Deck Options

### ISSUE THREAD

**Issue by lpnewey54** [ankidroid/Anki-Android#6599]
![Screenshot_20200625-054936_AnkiDroid](https://user-images.githubusercontent.com/46499597/86256928-bd4d2380-bb6d-11ea-80a8-28c34cb5f4ca.jpg)

collection.anki2.bak:
https://drive.google.com/file/d/1H2jm5SgxLfKNI4fzMXh3hRMAVbeY0A75/view?usp=sharing
###### Reproduction Steps

When syncing Anki the above (screenshot) message appears and nothing will return Anki to normal functionality. I have attempted to check database, restore from backup, full sync from server, and delete and reinstall. 

###### Debug info
I cannot access "Settings". 

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Reproduced. Stack trace:

```
2020-07-01 16:23:51.138 21361-21448/com.ichi2.anki E/CollectionTask: doInBackgroundLoadDeckCounts - error
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONObject com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object reference
        at com.ichi2.libanki.Decks.confForDid(Decks.java:669)
        at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:720)
        at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:225)
        at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:430)
        at com.ichi2.async.CollectionTask.doInBackgroundLoadDeckCounts(CollectionTask.java:553)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:261)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:76)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by david-allison-1** [comment]
@lpnewey54, what version of other Anki Clients are you using? Are you using any addons for Anki Desktop?

**Comment by david-allison-1** [comment]
@lpnewey54 Could you join our alpha program. This is fixed by "Check Database" in 2.12: https://docs.ankidroid.org/manual.html#betaTesting

Fix details: 4de7795423776b6a63d8215194507ac3ee6c5c28 #6454 #6455

**Comment by val59000** [comment]
Hi, unfortunately I'm struck with the same issue.
I tried the alpha version 2.12.0beta3 but the issue remains.
When the error popup show up I also tried to select the option to fully synchronized from the server but it always reproduce the same error "Collection not opened". Im completely locked out of using the app I can't import anything from my anki account.
Any suggestion ? Please tell me what you need to investigate. Thanks !

**Comment by david-allison-1** [comment]
Hi @val59000,

Have you tried "Check Database"?

If this fails, could you post a copy of your `collection.anki2` file? Either rename it to `.zip` and upload it here/Google Drive.

Or, if it contains information that you don't want to share publicly, could you send it to gmail: davidallisongithub

**Comment by val59000** [comment]
Hi, thanks for fast answer

Check Database seems to partially work. As mentionned is other similar issues, it actually makes the decks show up. But the issue reappears the next time I sync so I'm not convinced it has fixed anything and I'm afraid to lose my progress or have some kind of split brain issue regarding the syncing.

I have email you my collection exported from windows (email from val59000mc)

**Comment by david-allison-1** [comment]
@val59000 

Same stack trace

```
2020-07-06 22:32:42.174 28819-28913/com.ichi2.anki E/CollectionTask: doInBackgroundLoadDeckCounts - error
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONObject com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object reference
        at com.ichi2.libanki.Decks.confForDid(Decks.java:625)
        at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:721)
        at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:226)
        at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:425)
        at com.ichi2.async.CollectionTask.doInBackgroundLoadDeckCounts(CollectionTask.java:553)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:261)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:76)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

As mentioned in my email, the steps to fix this should be:

* (Anki Desktop) Backup your collection (incl. media)
* (Anki Desktop) Sync to upload to AnkiWeb
* (AnkiDroid) Full Download via **Settings-  Advanced - Force Full Sync - Download**
* (AnkiDroid) Check Database, then full upload to AnkiWeb
* (Anki Desktop) Full Download
* Syncing should now work with no issues.

Could you confirm that you've followed these steps. It should work as long as you perform the full upload via AnkiDroid.

I'm testing this now

**Comment by val59000** [comment]
Sorry I misread the instructions in the email, I thought I needed to upload from dektop and download to android, but you were saying the opposite. I tried what you said with the latest android backup I had and I was able to go back to a working state and successfully add the new deck I was trying to create tonight.
I'm still unsure of how I ended up with this error loop however. I'm now trying to create new decks and card types but cannot reproduce the issue. However now I'm using the latest alpha version  2.12.0beta3 on Android so I'm not in the exact same conditions.

**Comment by david-allison-1** [comment]
Definitely a duplicate of #6454 - still can't reproduce this on Anki Desktop

> As for some pointers of what I was doing. Everything was working great with 3 collections until tonight. And tonight I created on my computer a 4th collection "Russe vocabulaire" which is using a new card type I called "FR/RU/Commentaires" then added a few notes to these card type. THen I sync from desktop to Server. Then I sync on Android phone and got the error.

**Comment by david-allison-1** [comment]
@val59000 I still believe this is an Anki Desktop issue - I haven't done anything in the area (other than add the fix to "Check Database" to fix the issue). If you ever manage to reproduce this and have more information, it'd be great to know.

No worries! Happy studying :)

**Comment by david-allison-1** [comment]
@lpnewey54, is this still an issue in 2.12.X?
