### ISSUE TITLE
After submitting a special character like ὐ, the character displays as a square

### ISSUE THREAD

**Issue by thomasalvord** [ankidroid/Anki-Android#7896]
See this post that contains screenshots and a thorough description of this bug: https://groups.google.com/g/anki-android/c/wY_OiwQeIz8

###### Reproduction Steps

1.  Create a card with type: basic (type in the answer)
2.  On the front side put anything. On the backside put αὐτός
3. Now run Anki on ankidroid and load the card. Type αὐτός for the answer, then click submit.

###### Expected Result

This should show a match.

###### Actual Result

It shows a match but the answer I submit converts the ὐ and the checkmark into a square box.

###### Debug info

AnkiDroid Version = 2.14.2

Android Version = 9

ACRA UUID = 451fb701-f242-4c4e-8797-3f004b211614

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by thomasalvord** [comment]
> Hello! 👋 Thanks for logging this issue. Please remember we are all volunteers here, so some patience may be required before we can get to the issue. Also remember that the fastest way to get resolution on an issue is to propose a change directly, https://github.com/ankidroid/Anki-Android/wiki/Contributing

I would definitely propose a change if I knew how to code but I don't :(

**Comment by david-allison-1** [comment]
Hi @thomasalvord 

This works for me

* Settings - Advanced - Type answer into the card is disabled
* Tested "Show Answer"
* Tested copy/pasting the answer into the text box

Could you provide:

* An export of a card where this does not work 
    * Make a new deck
    * Make a note 
    * Long Press Deck in Deck Picker 
    * Export Deck 
    * zip the apkg
    * Upload the zip here as a comment

----

Testing was performed on 2.15alpha10

**Comment by thomasalvord** [comment]
Attached is the apkg, as well as an mp4 showing me creating a new deck, creating the card, then having this issue.

[20201213_121901.zip](https://github.com/ankidroid/Anki-Android/files/5685441/20201213_121901.zip)

**Comment by david-allison-1** [comment]
Thanks, this works fine on my Android 10 device. 

I'm testing now on an Android 9 emulator.

Could you make a new comment and paste the text which was on your clipboard when you pasted?

**Comment by thomasalvord** [comment]
You bet. Here it is: αὐτός

**Comment by thomasalvord** [comment]
You could also test any of these characters. These all have the same issue: ᾶἀἁᾳᾱᾰ

What's interesting is that these two characters (the acute and grave accents) do NOT have the issue but are also part of the greek characters: ὰά

**Comment by david-allison-1** [comment]
Reproduced on Android 9, I'll have a think. Please follow up if there's no movement on this within 3 days.

**Comment by david-allison-1** [comment]
Reproduced on an Android 10 emulator as well, interesting.

**Comment by thomasalvord** [comment]
I'm glad you were able to reproduce the issue, since without that it would be very difficult to troubleshoot.

I'm wonder if somehow the character set or encoding is different on the post-submission input field? Or perhaps the character set or encoding is different when processed during the submission? I wish I had some more know-how to help troubleshoot.

**Comment by david-allison-1** [comment]
<details><summary>HTML (no answer)</summary>

```
<style>.card {
 font-size: 14px;
 color: black;
 background-color: white;
 text-align: left;
}
</style>testing
<div><code id="typeans"><span class="typeMissed">&#945;&#8016;&#964;&#972;&#962;</span></code></div>

<hr id=answer>

αὐτός
```

</details>


<details><summary>HTML (with answer)</summary>

```
<style>.card {
 font-size: 14px;
 color: black;
 background-color: white;
 text-align: left;
}
</style>testing
<div><code id="typeans"><span class="typeGood">&#945;&#8016;&#964;&#972;&#962;</span><span id="typecheckmark">✔</span></code></div>

<hr id=answer>

αὐτός
```

</details>

The escaping happens: 

https://github.com/ankidroid/Anki-Android/blob/1f785c1b8c324266fdf652e84c9d9309d7278392/AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java#L60-L75

**Comment by david-allison-1** [comment]
@thomasalvord Is it possible for you to upgrade Android System WebView: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US (or the WebView which your system uses).

Your browser can render neither the checkmark character (block at the end of a correct answer) nor the greek character if it is HTML escaped.

My emulator only has issues with the greek character. This is fixable, but I'd prefer to say "upgrade your system" rather than adding in another option in advanced preferences, as we likely won't be able to sort out rendering the checkmark for you.

**Comment by david-allison-1** [comment]
Alternate note:

We moved from `CompatV15.detagged`:

https://github.com/ankidroid/Anki-Android/blob/13c27a6a1fa8465cc6656c67bd9db25afc7a51fa/AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java#L30-L38

to `Html.escapeHtml(str)`

We maybe should have moved to [TextUtils.htmlEncode](http://developer.android.com/reference/android/text/TextUtils.html#htmlEncode(java.lang.String))

See:

https://stackoverflow.com/questions/35104032/whats-the-difference-between-androids-html-escapehtml-and-textutils-htmlencode

**Comment by mikehardy** [comment]
Not saying which of Html.escapeHtml vs TextUtils.htmlEncode is better or not, but "we" didn't "move" to Html.escapeHtml, the way the Compat infrastructure works here, if API16 had Html.escapeHtml and CompatV16 implemented it (while CompatV15 did not) then everyone over API16 (which was...basically everyone) already got Html.escapeHtml. Implying this is not a new problem, it was there the whole time and maybe just not reported

**Comment by thomasalvord** [comment]
Android System WebView was disabled. From what I understood by a little research, android uses the Chrome app for webview and no longer uses Android System Webview. 

I had to disable the chrome app to be able to enable Android System Webview. I did that and Android System Webview updated. I then used Ankidroid but the same issues persisted. I even restarted my phone with these settings (don't know if that matters) and the same issues persisted.

If it is not an easy fix, I can live with the app turning some characters into squares.  I can still see if I entered the correct character because it will be highlighted green.

**Comment by mikehardy** [comment]
@thomasalvord I believe @david-allison-1 already proposed a fix for it, which I merged and should be out in the next alpha any minute now - you can check the "parallel" '.A' release (a side-by-side install that lets you test new code) https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha16 or sign up to help us by being an alpha tester (instructions here https://docs.ankidroid.org/manual.html#betaTesting ) and google will deliver it when they're done processing shortly

**Comment by thomasalvord** [comment]
I tested this apk https://github.com/ankidroid/Anki-Android/releases/download/v2.15alpha16/AnkiDroid-2.15alpha16.parallel.A.apk but the issue still persists.

**Comment by david-allison-1** [comment]
Dang, I'll take another look tonight. Thanks for the feedback

**Comment by mikehardy** [comment]
Most unexpected, yeah. @david-allison-1 before anything triple-check me on merge and release to make sure I didn't do something lame / out of order, I have reduced computing capability at the moment so my normal workbench and cross-check capability is much reduced. I might have made a mistake w/merge+release. I don't think so, but quick to check me

**Comment by david-allison-1** [comment]
Reproduced - shouldn't have trusted the unit test (although there'll be a speed improvement from the change in escaping, so I won't revert).

It's related to the `<code>` tag

```
<code>αὐτός</code>
αὐτός
```

The top has an issue, whereas the bottom works as expected

**Comment by thomasalvord** [comment]
@mikehardy and @david-allison-1 How do you work so diligently and quickly on this project, and as volunteers!?

**Comment by mikehardy** [comment]
All my pay work is on github these days so I'm in the notification loop anyway, and also (happily) our addition of a donation mechanism has resulted in an unexpected level of support so it is at least a bit financially rewarding. Motivation wise though I actually feel like this is some of the more meaningful work that I do because I know how it changes students lives (changed mine!) so it's fun and here I / we are 😁

**Comment by david-allison-1** [comment]
It's extremely impactful and meaningful work - that's motivation in itself and I wouldn't change it for the world. it's great for the soul.

Coupled with the fact that if you're experiencing a bug, then there's probably a few hundred people who didn't bother/weren't able to report it, and the fact that there's pretty much instant feedback so we know we're doing the right thing.

I've also got phone notifications enabled, which helps me keep on top of it.

PS: I'll get a code fix submitted in a couple of minutes - hopefully will be with you in an alpha by tomorrow - it'll be under "Advanced Preferences - Workarounds - Disable monospace typed answer formatting".

**Comment by thomasalvord** [comment]
Great! :)
