### ISSUE TITLE
[Bug] 2.15.4: CreateDeckDialog.createNewDeck - NullPointerException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9161]
From Google Play. Number 1 crash

```
java.lang.NullPointerException: 
  at android.content.ContextWrapper.getPackageName (ContextWrapper.java:142)
  at android.preference.PreferenceManager.getDefaultSharedPreferencesName (PreferenceManager.java:537)
  at android.preference.PreferenceManager.getDefaultSharedPreferences (PreferenceManager.java:526)
  at com.ichi2.anki.AnkiDroidApp.getSharedPrefs (AnkiDroidApp.java:371)
  at com.ichi2.anki.CollectionHelper.getCurrentAnkiDroidDirectory (CollectionHelper.java:263)
  at com.ichi2.anki.CollectionHelper.getCollectionPath (CollectionHelper.java:255)
  at com.ichi2.anki.CollectionHelper.getCol (CollectionHelper.java:122)
  at com.ichi2.anki.CollectionHelper.getCol (CollectionHelper.java:115)
  at com.ichi2.anki.AnkiActivity.getCol (AnkiActivity.java:157)
  at com.ichi2.anki.dialogs.CreateDeckDialog.createNewDeck (CreateDeckDialog.java:139)
  at com.ichi2.anki.dialogs.CreateDeckDialog.createDeck (CreateDeckDialog.java:114)
  at com.ichi2.anki.dialogs.CreateDeckDialog.onPositiveButtonClicked (CreateDeckDialog.java:153)
  at com.ichi2.anki.dialogs.CreateDeckDialog.lambda$showDialog$0 (CreateDeckDialog.java:99)
  at com.ichi2.anki.dialogs.CreateDeckDialog.lambda$showDialog$0$CreateDeckDialog (CreateDeckDialog.java)
  at com.ichi2.anki.dialogs.-$$Lambda$CreateDeckDialog$GT3-9pD_4kBO9MoWULdODVWg6UI.onClick (lambda:2)
  at com.afollestad.materialdialogs.MaterialDialog.onClick (MaterialDialog.java:410)
  at android.view.View.performClick (View.java:6659)
  at android.view.View.performClickInternal (View.java:6631)
  at android.view.View.access$3100 (View.java:790)
  at android.view.View$PerformClick.run (View.java:26187)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

**Comment by mikehardy** [comment]
That's troubling. I just checked the stack frames and it's as simple as you'd expect.

ContextWrapper defers the call to the base context (set via attachBaseContext or in constructor)
Somehow the creation of this ContextWrapper (whatever it is, where ever it is created) is happening with a base Context that is unexpectedly invalid (making the assumption that knowing your package name is something a Context should be able to do)

#8438 is the related PR that changed this area recently via git annotate, so it must be related assuming this stack is fresh

**Comment by mikehardy** [comment]
Here's an ACRA link to the same crash on an Android 11 Pixel 2XL (so we know this is fresh)  https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a78fcfe7-5380-4b53-ba21-e1e9ee842f44

logcat:

```


0 | --------- beginning of main
-- | --
1 | 06-29 13:42:09.035 I/AnkiDroid(20913): AbstractFlashcardViewer:: EASE_1 pressed
2 | 06-29 13:42:09.044 I/AnkiDroid(20913): Answering card 1516347483575
3 | 06-29  13:42:09.063 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE  cards SET  factor=?,lapses=?,did=?,due=?,ivl=?,mod=?,usn=?,left=?,odid=?,odue=?,reps=?,type=?,queue=?  WHERE id = ?
4 | 06-29 13:42:09.073 I/AnkiDroid(20913): Obtaining card
5 | 06-29 13:42:09.093 I/AnkiDroid(20913): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
6 | 06-29 13:42:09.104 I/AnkiDroid(20913): AbstractFlashcardViewer:: Question successfully shown for card id 1516347478988
7 | 06-29 13:42:10.336 I/AnkiDroid(20913): Play all: Completed - releasing sound
8 | 06-29 13:42:12.215 I/AnkiDroid(20913): Back key pressed
9 | 06-29 13:42:12.216 I/AnkiDroid(20913): finishWithAnimation END
10 | 06-29 13:42:12.235 I/AnkiDroid(20913): AnkiActivity::onPause - Reviewer
11 | 06-29 13:42:12.246 I/AnkiDroid(20913): Handling Activity Result: 901. Result: 50
12 | 06-29 13:42:12.246 I/AnkiDroid(20913): Creating notification channel with id/name: General Notifications/AnkiDroid
13 | 06-29 13:42:12.247 I/AnkiDroid(20913): Creating notification channel with id/name: Synchronization/Synchronization
14 | 06-29 13:42:12.247 I/AnkiDroid(20913): Creating notification channel with id/name: Global Reminders/Cards due
15 | 06-29 13:42:12.248 I/AnkiDroid(20913): Creating notification channel with id/name: Deck Reminders/Reminders
16 | 06-29 13:42:12.248 I/AnkiDroid(20913): AnkiActivity::onStart - DeckPicker
17 | 06-29 13:42:12.250 I/AnkiDroid(20913): AnkiActivity::onResume - DeckPicker
18 | 06-29 13:42:12.285 I/AnkiDroid(20913): Updating deck list UI
19 | 06-29 13:42:12.538 I/AnkiDroid(20913): AnkiActivity::onStop - Reviewer
20 | 06-29 13:42:12.539 I/AnkiDroid(20913): AnkiActivity::onDestroy - Reviewer
21 | 06-29 13:42:12.543 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?
22 | 06-29 13:42:12.556 I/AnkiDroid(20913): flush - Saving information to DB...
23 | 06-29 13:42:12.556 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
24 | 06-29 13:42:34.444 I/AnkiDroid(20913): DeckPicker:: Sync button pressed
25 | 06-29 13:42:34.471 I/AnkiDroid(20913): Locked Collection - Collection Loading should fail
26 | 06-29 13:42:34.471 I/AnkiDroid(20913): Sync - starting sync
27 | 06-29 13:42:34.698 I/AnkiDroid(20913): Rust: transaction begin
28 | 06-29 13:42:34.698 I/AnkiDroid(20913): Sync: getting meta data from server
29 | 06-29 13:42:34.699 I/AnkiDroid(20913): Sync: building local meta data
30 | 06-29 13:42:34.838 I/AnkiDroid(20913): Sync: collection removed data
31 | 06-29 13:42:34.839 I/AnkiDroid(20913): Sync: sending and receiving removed data
32 | 06-29 13:42:34.898 I/AnkiDroid(20913): Sync: applying removed data
33 | 06-29 13:42:34.898 I/AnkiDroid(20913): Sync: collection small changes
34 | 06-29 13:42:34.898 I/AnkiDroid(20913): Sync: sending and receiving small changes
35 | 06-29 13:42:34.949 I/AnkiDroid(20913): Sync: merging small changes
36 | 06-29 13:42:34.949 I/AnkiDroid(20913): Sync: downloading chunked data
37 | 06-29 13:42:34.998 I/AnkiDroid(20913): Sync: applying chunked data
38 | 06-29 13:42:34.999 I/AnkiDroid(20913): Sync: collecting chunked data
39 | 06-29 13:42:35.001 I/AnkiDroid(20913): Sync: sending chunked data
40 | 06-29 13:42:35.154 I/AnkiDroid(20913): Sync: sending finish command
41 | 06-29 13:42:35.209 I/AnkiDroid(20913): Sync: finishing
42 | 06-29 13:42:35.214 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE col SET models=?
43 | 06-29 13:42:35.224 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?
44 | 06-29 13:42:35.227 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE col SET tags=?
45 | 06-29 13:42:35.228 I/AnkiDroid(20913): flush - Saving information to DB...
46 | 06-29 13:42:35.228 I/AnkiDroid(20913): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
47 | 06-29 13:42:35.229 I/AnkiDroid(20913): Rust: transaction commit
48 | 06-29 13:42:35.246 I/AnkiDroid(20913): Sync - Performing media sync
49 | 06-29 13:42:35.474 I/AnkiDroid(20913): Sync Finished - Closing Collection
50 | 06-29 13:42:35.474 W/AnkiDroid(20913): DB/ Not in a transaction. Cannot end transaction.
51 | 06-29 13:42:35.474 I/AnkiDroid(20913): ExecuteCommand: closeCollection
52 | 06-29 13:42:35.484 I/AnkiDroid(20913): Closing Collection Log
53 | 06-29 13:42:35.484 I/AnkiDroid(20913): Collection closed
54 | 06-29 13:42:35.484 I/AnkiDroid(20913): Unlocked Collection
55 | 06-29  13:42:35.504 I/AnkiDroid(20913): Sync Listener: onPostExecute: Data:  Payload{mTaskType=1, data=[null, com.ichi2.libanki.Collection@13cdd73,  null], resultType=null, result=null, success=true, returnType=0,  exception=null, message=''}
56 | 06-29 13:42:35.504 I/AnkiDroid(20913): Sync was successful
57 | 06-29 13:42:35.504 I/AnkiDroid(20913): Regular sync completed successfully
58 | 06-29 13:42:35.509 I/AnkiDroid(20913): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
59 | 06-29 13:42:35.509 I/AnkiDroid(20913): Opening rust backend. Server: false. Langs: 'en', path:
60 | 06-29 13:42:35.511 I/AnkiDroid(20913): Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
61 | 06-29 13:42:35.687 I/AnkiDroid(20913): Opening Collection Log
62 | 06-29 13:42:35.700 I/AnkiDroid(20913): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
63 | 06-29 13:42:35.728 I/AnkiDroid(20913): Updating deck list UI
64 | 06-29 13:42:44.820 I/AnkiDroid(20913): Pull to Sync: Syncing
65 | 06-29 13:42:44.844 I/AnkiDroid(20913): Locked Collection - Collection Loading should fail
66 | 06-29 13:42:44.844 I/AnkiDroid(20913): Sync - starting sync
67 | 06-29 13:42:45.109 I/AnkiDroid(20913): Rust: transaction begin
68 | 06-29 13:42:45.109 I/AnkiDroid(20913): Sync: getting meta data from server
69 | 06-29 13:42:45.110 I/AnkiDroid(20913): Sync: building local meta data
70 | 06-29 13:42:45.111 I/AnkiDroid(20913): Sync: no changes - returning
71 | 06-29 13:42:45.111 I/AnkiDroid(20913): Rust: transaction rollback
72 | 06-29 13:42:45.111 I/AnkiDroid(20913): Sync - Performing media sync
73 | 06-29 13:42:45.333 I/AnkiDroid(20913): Sync Finished - Closing Collection
74 | 06-29 13:42:45.334 W/AnkiDroid(20913): DB/ Not in a transaction. Cannot end transaction.
75 | 06-29 13:42:45.334 I/AnkiDroid(20913): ExecuteCommand: closeCollection
76 | 06-29 13:42:45.339 I/AnkiDroid(20913): Closing Collection Log
77 | 06-29 13:42:45.340 I/AnkiDroid(20913): Collection closed
78 | 06-29 13:42:45.340 I/AnkiDroid(20913): Unlocked Collection
79 | 06-29  13:42:45.357 I/AnkiDroid(20913): Sync Listener: onPostExecute: Data:  Payload{mTaskType=1, data=[5kP1qHcOSaZwTCJs, true, null,  com.ichi2.anki.web.PreferenceBackedHostNum@9ec5b0d],  resultType=noChanges, result=[], success=false, returnType=0,  exception=null, message=''}
80 | 06-29 13:43:01.786 I/AnkiDroid(20913): CreateDeckDialog::createNewDeck
81 | --------- beginning of crash

```

**Comment by Akshay0701** [comment]
#8438 yes this was a recent change on deck creation code, 

most probably in the `CreateDeckDialog `class mAnkiActivity variable is not properly initialized in some cases (I am not sure for now), will fragmentFactory here? 

are there any steps to reproduce in our devices?

**Comment by dorrin-sot** [comment]
> #8438 yes this was a recent change on deck creation code,
> 
> most probably in the `CreateDeckDialog `class mAnkiActivity variable is not properly initialized in some cases (I am not sure for now),
> 
> should we use fragmentFactory here?
> 
> are there any steps to reproduce in our devices?

I tried to reproduce it and found that if you sync via the button and then sync via pulling the screen down gesture, and then try to create a deck the crash happens

**Comment by Akshay0701** [comment]
> > are there any steps to reproduce in our devices?
> 
> I tried to reproduce it and found that if you sync via the button and then sync via pulling the screen down gesture, and then try to create a deck the crash happens

thank you so much, this helped and now I fixed it.

**Comment by david-allison-1** [comment]
Still seeing similar crashes in ACRA for 2.15.5

@mikehardy just confirming this went in before I investigate further

**Comment by mikehardy** [comment]
Was picked, yes, as far as I know 🤔

**Comment by david-allison-1** [comment]
@mikehardy Could you check the below

Ref: #9163

Contains two commits

https://github.com/ankidroid/Anki-Android/commit/a57f063018f82bf2473261c5d156cf060057d284 and https://github.com/ankidroid/Anki-Android/commit/d36a76c02526236b9a5e5d499e94f89f844e8387

a57f063018f82bf2473261c5d156cf060057d284  -> 2e3dcae3b30c4dd5f43bb7c8aa3be7a774aec056
d36a76c02526236b9a5e5d499e94f89f844e8387 -> ?

**Comment by mikehardy** [comment]
Dangit. Did a complete audit of the picks - also missed this #9036 

This one here points at a process flaw I had - it is difficult to tell just from the PR itself if something was squash-merged or not, and there have been a lot of those. I was lulled into thinking 9163 was 2 commits squashed to one so I just looked at the single commit github mentions is merged to master (regardless of how many are merged to master, only one is mentioned). So I need to be a lot more careful about that - only valid way is to look at the commit list on the PR while comparing it to the main branch history for confirmation.

The second one (unrelated to this, but related via process failure) was simply missed yet I labeled it, I wonder if I got working trees crossed up locally (that's why I did the full audit).

Anyway. The current build is still rolling out and I think 2.16 will be a while so it's not too traumatic to push another build out to play store at least. I'll true up the picks and do it.

**Comment by mikehardy** [comment]
Oh - on further inspection the unrelated one I thought I missed (9036) was in there, it was milestoned incorrectly, it went out with 2.15.4.

So, just a squash-merge vs rebase-merge commit list verification failure on my part for the one commit. Le sigh
